// =====================================================================
// Centralized mock data for AI Tools Directory
// Used both at runtime (no DB needed) and for seeding
// =====================================================================

export type Tool = {
  id: string;
  slug: string;
  name: string;
  tagline: string;
  description: string;
  longDescription: string;
  websiteUrl: string;
  logoUrl: string;
  bannerUrl?: string;
  pricingType: "FREE" | "FREEMIUM" | "PAID" | "FREE_TRIAL" | "CONTACT_PRICING";
  startingPrice?: number;
  currency: string;
  freeTrial: boolean;
  freeTrialDays?: number;
  rating: number;
  reviewCount: number;
  viewCount: number;
  clickCount: number;
  bookmarkCount: number;
  featured: boolean;
  sponsored: boolean;
  verified: boolean;
  launchedAt: string;
  categorySlug: string;
  tags: string[];
  features: string[];
  pricingPlans: {
    name: string;
    price: number;
    period: "MONTHLY" | "YEARLY" | "ONE_TIME";
    features: string[];
    isPopular?: boolean;
  }[];
};

export type Category = {
  id: string;
  slug: string;
  name: string;
  description: string;
  icon: string;
  color: string;
  toolCount: number;
  isFeatured: boolean;
};

export const CATEGORIES: Category[] = [
  { id: "c1", slug: "writing", name: "Writing & Content", description: "AI tools for writing, copywriting, and content creation", icon: "PenLine", color: "violet", toolCount: 1842, isFeatured: true },
  { id: "c2", slug: "image", name: "Image Generation", description: "Generate, edit, and enhance images with AI", icon: "ImageIcon", color: "pink", toolCount: 1267, isFeatured: true },
  { id: "c3", slug: "video", name: "Video & Animation", description: "Create, edit, and animate videos with AI", icon: "Video", color: "rose", toolCount: 893, isFeatured: true },
  { id: "c4", slug: "code", name: "Code & Development", description: "AI coding assistants, code generation, dev tools", icon: "Code2", color: "emerald", toolCount: 1456, isFeatured: true },
  { id: "c5", slug: "chat", name: "Chatbots & Assistants", description: "Conversational AI, virtual assistants, chatbots", icon: "MessageSquare", color: "blue", toolCount: 2104, isFeatured: true },
  { id: "c6", slug: "audio", name: "Audio & Music", description: "Voice synthesis, music generation, audio editing", icon: "Music", color: "amber", toolCount: 678, isFeatured: true },
  { id: "c7", slug: "productivity", name: "Productivity", description: "AI tools to boost your personal and team productivity", icon: "Zap", color: "orange", toolCount: 1934, isFeatured: true },
  { id: "c8", slug: "marketing", name: "Marketing & SEO", description: "AI for marketing automation, SEO, and growth", icon: "TrendingUp", color: "green", toolCount: 1123, isFeatured: true },
  { id: "c9", slug: "design", name: "Design & UX", description: "AI-powered design tools, UI/UX, branding", icon: "Palette", color: "purple", toolCount: 987, isFeatured: true },
  { id: "c10", slug: "data", name: "Data & Analytics", description: "AI for data analysis, visualization, and insights", icon: "BarChart3", color: "cyan", toolCount: 743, isFeatured: true },
  { id: "c11", slug: "research", name: "Research & Education", description: "AI tools for learning, research, and academia", icon: "GraduationCap", color: "teal", toolCount: 654, isFeatured: false },
  { id: "c12", slug: "business", name: "Business & Operations", description: "AI for HR, finance, ops, and enterprise workflows", icon: "Briefcase", color: "slate", toolCount: 1289, isFeatured: false },
];

const ICON_BASE = "https://api.dicebear.com/7.x/shapes/svg?seed=";

export const TOOLS: Tool[] = [
  {
    id: "t1",
    slug: "chatgpt",
    name: "ChatGPT",
    tagline: "Conversational AI assistant by OpenAI",
    description: "Advanced AI chatbot capable of natural conversations, code generation, analysis, and more.",
    longDescription: "ChatGPT is a leading conversational AI developed by OpenAI. It can engage in natural language conversations, answer questions, write and debug code, draft content, analyze data, and perform a wide range of tasks. Powered by GPT-4, it supports multimodal input including text, images, and voice.",
    websiteUrl: "https://chat.openai.com",
    logoUrl: "https://api.dicebear.com/7.x/shapes/svg?seed=chatgpt&backgroundColor=10a37f",
    pricingType: "FREEMIUM",
    startingPrice: 20,
    currency: "USD",
    freeTrial: true,
    rating: 4.8,
    reviewCount: 12453,
    viewCount: 8942341,
    clickCount: 2341892,
    bookmarkCount: 89234,
    featured: true,
    sponsored: false,
    verified: true,
    launchedAt: "2022-11-30",
    categorySlug: "chat",
    tags: ["OpenAI", "GPT-4", "Assistant", "Multimodal"],
    features: ["GPT-4 Turbo", "Code Interpreter", "Web Browsing", "DALL-E Integration", "Voice Mode", "Custom GPTs", "Plugin Ecosystem"],
    pricingPlans: [
      { name: "Free", price: 0, period: "MONTHLY", features: ["GPT-3.5 access", "Standard response time", "Limited messages"] },
      { name: "Plus", price: 20, period: "MONTHLY", features: ["GPT-4 access", "Faster response time", "GPT-4 Turbo", "DALL-E", "Code Interpreter", "Web Browsing"], isPopular: true },
      { name: "Team", price: 25, period: "MONTHLY", features: ["Higher message limits", "Shared workspace", "Admin console", "Priority support"] },
    ],
  },
  {
    id: "t2",
    slug: "midjourney",
    name: "Midjourney",
    tagline: "AI image generation with artistic flair",
    description: "Create stunning AI-generated artwork from text prompts with unique artistic styles.",
    longDescription: "Midjourney is an independent research lab that produces a proprietary artificial intelligence program that creates images from textual descriptions. Known for its distinctive artistic style, Midjourney excels at creating highly stylized, painterly images that have a unique aesthetic appeal.",
    websiteUrl: "https://midjourney.com",
    logoUrl: "https://api.dicebear.com/7.x/shapes/svg?seed=midjourney&backgroundColor=4d4d4d",
    pricingType: "PAID",
    startingPrice: 10,
    currency: "USD",
    freeTrial: false,
    rating: 4.7,
    reviewCount: 8923,
    viewCount: 5621893,
    clickCount: 1782341,
    bookmarkCount: 67123,
    featured: true,
    sponsored: false,
    verified: true,
    launchedAt: "2022-07-12",
    categorySlug: "image",
    tags: ["AI Art", "Image Generation", "Discord"],
    features: ["V6 Model", "Style References", "Character References", "Variations", "Upscaling", "Pan & Zoom", "Remix Mode"],
    pricingPlans: [
      { name: "Basic", price: 10, period: "MONTHLY", features: ["3.3 hours of GPU time", "Commercial terms", "Web interface access"] },
      { name: "Standard", price: 30, period: "MONTHLY", features: ["15 hours of GPU time", "Unlimited relaxed generations", "Commercial terms"], isPopular: true },
      { name: "Pro", price: 60, period: "MONTHLY", features: ["30 hours of GPU time", "Unlimited relaxed generations", "Stealth mode", "12 priority image generations"] },
    ],
  },
  {
    id: "t3",
    slug: "claude",
    name: "Claude",
    tagline: "AI assistant by Anthropic",
    description: "Helpful, harmless, and honest AI assistant for writing, analysis, and coding.",
    longDescription: "Claude is a next-generation AI assistant built by Anthropic. It is designed to be helpful, harmless, and honest. Claude can handle a wide variety of tasks including writing, analysis, coding, math, and creative work. It features a 200K token context window and excels at following complex instructions.",
    websiteUrl: "https://claude.ai",
    logoUrl: "https://api.dicebear.com/7.x/shapes/svg?seed=claude&backgroundColor=d97757",
    pricingType: "FREEMIUM",
    startingPrice: 20,
    currency: "USD",
    freeTrial: true,
    rating: 4.9,
    reviewCount: 5234,
    viewCount: 3412893,
    clickCount: 923481,
    bookmarkCount: 45213,
    featured: true,
    sponsored: false,
    verified: true,
    launchedAt: "2023-03-14",
    categorySlug: "chat",
    tags: ["Anthropic", "Claude 3", "Long Context", "Analysis"],
    features: ["200K Context Window", "Claude 3 Opus", "Claude 3 Sonnet", "Claude 3 Haiku", "Vision Capabilities", "Tool Use", "Artifacts"],
    pricingPlans: [
      { name: "Free", price: 0, period: "MONTHLY", features: ["Claude 3.5 Sonnet access", "Daily message limit", "Standard response time"] },
      { name: "Pro", price: 20, period: "MONTHLY", features: ["5x more usage", "Priority access", "Claude 3 Opus", "Early access to features"], isPopular: true },
      { name: "Team", price: 30, period: "MONTHLY", features: ["Higher usage limits", "Team workspace", "Admin tools", "Billing consolidation"] },
    ],
  },
  {
    id: "t4",
    slug: "github-copilot",
    name: "GitHub Copilot",
    tagline: "Your AI pair programmer",
    description: "AI-powered code completion and generation directly in your editor.",
    longDescription: "GitHub Copilot uses the OpenAI Codex to suggest code and functions in real-time as you type. It integrates seamlessly with popular IDEs like VS Code, Visual Studio, Neovim, and JetBrains. Copilot helps developers write code faster, learn new languages, and reduce repetitive tasks.",
    websiteUrl: "https://github.com/features/copilot",
    logoUrl: "https://api.dicebear.com/7.x/shapes/svg?seed=copilot&backgroundColor=24292e",
    pricingType: "PAID",
    startingPrice: 10,
    currency: "USD",
    freeTrial: true,
    freeTrialDays: 30,
    rating: 4.6,
    reviewCount: 6789,
    viewCount: 4231892,
    clickCount: 1234892,
    bookmarkCount: 52341,
    featured: true,
    sponsored: false,
    verified: true,
    launchedAt: "2021-06-29",
    categorySlug: "code",
    tags: ["GitHub", "OpenAI", "Code Completion", "IDE"],
    features: ["Code Completion", "Copilot Chat", "PR Summaries", "Copilot CLI", "Multi-language Support", "Test Generation", "Code Translation"],
    pricingPlans: [
      { name: "Individual", price: 10, period: "MONTHLY", features: ["Code completions", "Copilot Chat", "IDE integration"] },
      { name: "Business", price: 19, period: "MONTHLY", features: ["Everything in Individual", "Organization policy management", "Audit logs", "IP indemnity"], isPopular: true },
      { name: "Enterprise", price: 39, period: "MONTHLY", features: ["Everything in Business", "Custom models", "Enterprise security", "Pull request summaries"] },
    ],
  },
  {
    id: "t5",
    slug: "runway",
    name: "Runway",
    tagline: "AI video generation and editing",
    description: "Create stunning videos with text-to-video, image-to-video, and AI editing tools.",
    longDescription: "Runway is an applied AI research company building tools for content creation. Their Gen-2 model can generate videos from text prompts, transform images into videos, and apply various AI-powered video editing effects. Runway is used by filmmakers, designers, and creators worldwide.",
    websiteUrl: "https://runwayml.com",
    logoUrl: "https://api.dicebear.com/7.x/shapes/svg?seed=runway&backgroundColor=000000",
    pricingType: "FREEMIUM",
    startingPrice: 15,
    currency: "USD",
    freeTrial: true,
    rating: 4.5,
    reviewCount: 3421,
    viewCount: 2341892,
    clickCount: 623481,
    bookmarkCount: 34213,
    featured: true,
    sponsored: true,
    verified: true,
    launchedAt: "2020-12-15",
    categorySlug: "video",
    tags: ["Video Generation", "Gen-2", "AI Editing"],
    features: ["Gen-2 Text-to-Video", "Image-to-Video", "Video-to-Video", "Motion Brush", "Camera Controls", "Inpainting", "Green Screen"],
    pricingPlans: [
      { name: "Free", price: 0, period: "MONTHLY", features: ["3 projects", "125 credits", "Watermarked exports"] },
      { name: "Standard", price: 15, period: "MONTHLY", features: ["Unlimited projects", "625 credits/month", "No watermark"], isPopular: true },
      { name: "Pro", price: 35, period: "MONTHLY", features: ["Everything in Standard", "2250 credits/month", "16K upscales", "Premium support"] },
    ],
  },
  {
    id: "t6",
    slug: "jasper",
    name: "Jasper",
    tagline: "AI content platform for marketing teams",
    description: "Enterprise-grade AI writing assistant for marketing and content creation.",
    longDescription: "Jasper is an AI content platform that helps marketing teams create on-brand content at scale. It offers templates for blogs, ads, emails, and more, with features like brand voice, SEO mode, and team collaboration. Trusted by 70,000+ teams worldwide.",
    websiteUrl: "https://jasper.ai",
    logoUrl: "https://api.dicebear.com/7.x/shapes/svg?seed=jasper&backgroundColor=8b5cf6",
    pricingType: "PAID",
    startingPrice: 39,
    currency: "USD",
    freeTrial: true,
    freeTrialDays: 7,
    rating: 4.4,
    reviewCount: 4521,
    viewCount: 1842934,
    clickCount: 523481,
    bookmarkCount: 28413,
    featured: false,
    sponsored: true,
    verified: true,
    launchedAt: "2021-01-20",
    categorySlug: "writing",
    tags: ["Marketing", "Copywriting", "Brand Voice"],
    features: ["Brand Voice", "50+ Templates", "SEO Mode", "Team Collaboration", "Campaigns", "Browser Extension", "API Access"],
    pricingPlans: [
      { name: "Creator", price: 39, period: "MONTHLY", features: ["1 brand voice", "50+ templates", "Browser extension"] },
      { name: "Pro", price: 59, period: "MONTHLY", features: ["3 brand voices", "SEO mode", "Campaigns", "API access"], isPopular: true },
      { name: "Business", price: 499, period: "MONTHLY", features: ["Custom brand voices", "SSO", "Custom templates", "Dedicated success manager"] },
    ],
  },
  {
    id: "t7",
    slug: "elevenlabs",
    name: "ElevenLabs",
    tagline: "Realistic AI voice generation",
    description: "Generate lifelike voices, clone voices, and create audio content with AI.",
    longDescription: "ElevenLabs is the leading AI voice generator and text-to-speech platform. It can generate highly realistic voices in 29 languages, clone voices from short samples, and create natural-sounding audio content. Used by audiobook publishers, game developers, and content creators.",
    websiteUrl: "https://elevenlabs.io",
    logoUrl: "https://api.dicebear.com/7.x/shapes/svg?seed=eleven&backgroundColor=000000",
    pricingType: "FREEMIUM",
    startingPrice: 5,
    currency: "USD",
    freeTrial: true,
    rating: 4.7,
    reviewCount: 2841,
    viewCount: 1234892,
    clickCount: 423481,
    bookmarkCount: 23421,
    featured: true,
    sponsored: false,
    verified: true,
    launchedAt: "2022-01-23",
    categorySlug: "audio",
    tags: ["Voice Cloning", "TTS", "Multilingual"],
    features: ["Text-to-Speech", "Voice Cloning", "29 Languages", "Sound Effects", "AI Dubbing", "Voice Library", "Studio Editor"],
    pricingPlans: [
      { name: "Free", price: 0, period: "MONTHLY", features: ["10K credits/month", "Commercial license", "Voice library access"] },
      { name: "Starter", price: 5, period: "MONTHLY", features: ["30K credits/month", "Voice cloning", "Audio projects"], isPopular: true },
      { name: "Creator", price: 22, period: "MONTHLY", features: ["100K credits/month", "Professional voice cloning", "Projects API"] },
    ],
  },
  {
    id: "t8",
    slug: "perplexity",
    name: "Perplexity",
    tagline: "AI-powered answer engine",
    description: "Get accurate, cited answers to any question with real-time web search.",
    longDescription: "Perplexity is an AI-powered answer engine that provides accurate, real-time information with citations. It combines the power of large language models with live web search to deliver trustworthy answers. Features include Copilot mode, file uploads, and focused search collections.",
    websiteUrl: "https://perplexity.ai",
    logoUrl: "https://api.dicebear.com/7.x/shapes/svg?seed=perplexity&backgroundColor=1fb8cd",
    pricingType: "FREEMIUM",
    startingPrice: 20,
    currency: "USD",
    freeTrial: false,
    rating: 4.6,
    reviewCount: 3421,
    viewCount: 2341892,
    clickCount: 723481,
    bookmarkCount: 31203,
    featured: false,
    sponsored: false,
    verified: true,
    launchedAt: "2022-12-07",
    categorySlug: "research",
    tags: ["Search", "Citations", "Real-time"],
    features: ["Pro Search", "Copilot Mode", "File Uploads", "Focus Modes", "Collections", "Image Generation", "API Access"],
    pricingPlans: [
      { name: "Free", price: 0, period: "MONTHLY", features: ["Unlimited quick searches", "5 Pro searches/day", "Basic models"] },
      { name: "Pro", price: 20, period: "MONTHLY", features: ["300+ Pro searches/day", "File uploads", "GPT-4, Claude 3, Opus", "Image generation"], isPopular: true },
      { name: "Enterprise", price: 40, period: "MONTHLY", features: ["Unlimited Pro searches", "Internal data search", "Team management", "SSO"] },
    ],
  },
  {
    id: "t9",
    slug: "notion-ai",
    name: "Notion AI",
    tagline: "AI assistant built into Notion",
    description: "Write, summarize, translate, and brainstorm directly within your Notion workspace.",
    longDescription: "Notion AI is an integrated AI assistant that helps you write, summarize, translate, and brainstorm directly within your Notion workspace. It can improve existing content, generate new ideas, and automate repetitive writing tasks. Available as an add-on to any Notion plan.",
    websiteUrl: "https://notion.so/product/ai",
    logoUrl: "https://api.dicebear.com/7.x/shapes/svg?seed=notion&backgroundColor=000000",
    pricingType: "PAID",
    startingPrice: 10,
    currency: "USD",
    freeTrial: true,
    freeTrialDays: 14,
    rating: 4.5,
    reviewCount: 5621,
    viewCount: 3123941,
    clickCount: 892341,
    bookmarkCount: 41234,
    featured: false,
    sponsored: false,
    verified: true,
    launchedAt: "2023-02-22",
    categorySlug: "productivity",
    tags: ["Notion", "Writing", "Productivity"],
    features: ["AI Writing", "Summarization", "Translation", "Q&A", "Auto-fill Tables", "Brainstorming", "Meeting Notes"],
    pricingPlans: [
      { name: "Add-on", price: 10, period: "MONTHLY", features: ["Unlimited AI responses", "Works with any Notion plan", "Priority processing"] },
    ],
  },
  {
    id: "t10",
    slug: "stable-diffusion",
    name: "Stable Diffusion",
    tagline: "Open-source AI image generation",
    description: "Generate high-quality images locally or via API with this open-source model.",
    longDescription: "Stable Diffusion is an open-source latent text-to-image diffusion model capable of generating photorealistic images from text prompts. It can be run locally on consumer hardware, making it popular among developers and artists. The ecosystem includes SDXL, ControlNet, LoRA training, and more.",
    websiteUrl: "https://stability.ai",
    logoUrl: "https://api.dicebear.com/7.x/shapes/svg?seed=stable&backgroundColor=9333ea",
    pricingType: "FREE",
    startingPrice: 0,
    currency: "USD",
    freeTrial: false,
    rating: 4.6,
    reviewCount: 7823,
    viewCount: 5621893,
    clickCount: 1348923,
    bookmarkCount: 67234,
    featured: true,
    sponsored: false,
    verified: true,
    launchedAt: "2022-08-22",
    categorySlug: "image",
    tags: ["Open Source", "Self-hosted", "SDXL", "ControlNet"],
    features: ["SDXL Model", "ControlNet", "LoRA Training", "Image-to-Image", "Inpainting", "Upscaling", "API Access"],
    pricingPlans: [
      { name: "Community", price: 0, period: "MONTHLY", features: ["Open source models", "Self-hosting", "Community support"] },
      { name: "Pro", price: 9, period: "MONTHLY", features: ["API access", "Premium models", "Faster generation"], isPopular: true },
      { name: "Enterprise", price: 99, period: "MONTHLY", features: ["Dedicated GPUs", "Custom models", "SLA", "Priority support"] },
    ],
  },
  {
    id: "t11",
    slug: "synthesia",
    name: "Synthesia",
    tagline: "Create AI videos with avatars",
    description: "Generate professional videos with AI avatars in 120+ languages without a camera.",
    longDescription: "Synthesia is an AI video generation platform that lets you create professional videos using AI avatars. Type your script, choose an avatar, and generate a video in minutes. Perfect for training, marketing, and internal communications. Supports 120+ languages and 140+ AI avatars.",
    websiteUrl: "https://synthesia.io",
    logoUrl: "https://api.dicebear.com/7.x/shapes/svg?seed=synthesia&backgroundColor=dc2626",
    pricingType: "PAID",
    startingPrice: 29,
    currency: "USD",
    freeTrial: true,
    freeTrialDays: 14,
    rating: 4.4,
    reviewCount: 2341,
    viewCount: 1234892,
    clickCount: 423481,
    bookmarkCount: 21342,
    featured: false,
    sponsored: true,
    verified: true,
    launchedAt: "2017-12-15",
    categorySlug: "video",
    tags: ["Video Avatars", "Multilingual", "Corporate"],
    features: ["140+ AI Avatars", "120+ Languages", "Custom Avatars", "Templates", "Voice Cloning", "Screen Recording", "Collaboration"],
    pricingPlans: [
      { name: "Starter", price: 29, period: "MONTHLY", features: ["10 min/month", "70+ AI avatars", "120+ languages"] },
      { name: "Creator", price: 89, period: "MONTHLY", features: ["30 min/month", "140+ avatars", "Custom avatars", "No watermark"], isPopular: true },
      { name: "Enterprise", price: 0, period: "MONTHLY", features: ["Custom minutes", "SSO", "Premium avatars", "Dedicated support"] },
    ],
  },
  {
    id: "t12",
    slug: "grammarly",
    name: "Grammarly",
    tagline: "AI-powered writing assistant",
    description: "Improve your writing with AI-powered grammar, tone, and style suggestions.",
    longDescription: "Grammarly is an AI-powered writing assistant that helps you write with confidence. It checks grammar, spelling, and punctuation in real-time, suggests vocabulary improvements, and provides tone adjustments. GrammarlyGO brings generative AI to compose, rewrite, and ideate.",
    websiteUrl: "https://grammarly.com",
    logoUrl: "https://api.dicebear.com/7.x/shapes/svg?seed=grammarly&backgroundColor=15c39a",
    pricingType: "FREEMIUM",
    startingPrice: 12,
    currency: "USD",
    freeTrial: true,
    rating: 4.5,
    reviewCount: 12341,
    viewCount: 8921341,
    clickCount: 2341892,
    bookmarkCount: 78234,
    featured: false,
    sponsored: false,
    verified: true,
    launchedAt: "2009-07-01",
    categorySlug: "writing",
    tags: ["Grammar", "Style", "Tone Detection"],
    features: ["Grammar Check", "Tone Detection", "Plagiarism Checker", "GrammarlyGO AI", "Browser Extension", "Citations", "Goals"],
    pricingPlans: [
      { name: "Free", price: 0, period: "MONTHLY", features: ["Basic grammar", "Spelling", "Punctuation"] },
      { name: "Premium", price: 12, period: "MONTHLY", features: ["Advanced suggestions", "Tone adjustments", "Plagiarism checker", "Vocabulary"], isPopular: true },
      { name: "Business", price: 15, period: "MONTHLY", features: ["Style guide", "Brand tones", "Analytics", "Admin console"] },
    ],
  },
];

export type PricingTier = {
  name: string;
  monthly: number;
  yearly: number;
  description: string;
  features: string[];
  isPopular: boolean;
  cta: string;
  highlight?: boolean;
};

export const PLATFORM_PRICING_TIERS: PricingTier[] = [
  {
    name: "Free",
    monthly: 0,
    yearly: 0,
    description: "Perfect for individuals exploring AI tools",
    features: ["Browse 100K+ AI tools", "Basic search & filters", "Save up to 25 bookmarks", "1 public collection", "Community access", "Weekly newsletter"],
    isPopular: false,
    cta: "Get Started Free",
  },
  {
    name: "Pro",
    monthly: 19,
    yearly: 15,
    description: "For power users and content creators",
    features: ["Everything in Free", "Unlimited bookmarks & collections", "Advanced AI search", "Tool comparison (up to 5)", "Personal AI recommendations", "Early access to new tools", "Priority support", "No ads"],
    isPopular: true,
    cta: "Start Pro Trial",
    highlight: true,
  },
  {
    name: "Business",
    monthly: 79,
    yearly: 65,
    description: "For teams and growing businesses",
    features: ["Everything in Pro", "Up to 10 team members", "Shared collections", "Team analytics dashboard", "API access (10K calls/mo)", "Custom collections", "SSO authentication", "Dedicated support"],
    isPopular: false,
    cta: "Start Business Trial",
  },
  {
    name: "Enterprise",
    monthly: 299,
    yearly: 249,
    description: "For large organizations with custom needs",
    features: ["Everything in Business", "Unlimited team members", "White-label branding", "Custom integrations", "Dedicated account manager", "99.9% SLA", "On-premise deployment", "Custom AI models"],
    isPopular: false,
    cta: "Contact Sales",
  },
];

export type Review = {
  id: string;
  toolId: string;
  userName: string;
  userAvatar: string;
  rating: number;
  title: string;
  content: string;
  helpfulCount: number;
  verified: boolean;
  createdAt: string;
};

export const REVIEWS: Review[] = [
  { id: "r1", toolId: "t1", userName: "Sarah Chen", userAvatar: "SC", rating: 5, title: "Indispensable for daily work", content: "ChatGPT has completely transformed how I approach problem-solving. From drafting emails to brainstorming content ideas, it's become my go-to assistant. The GPT-4 model is remarkably capable.", helpfulCount: 234, verified: true, createdAt: "2024-01-15" },
  { id: "r2", toolId: "t1", userName: "Marcus Rodriguez", userAvatar: "MR", rating: 4, title: "Powerful but pricey", content: "Incredible tool for coding and analysis. The code interpreter alone is worth the subscription. Only downside is the usage cap on the Plus plan during peak hours.", helpfulCount: 156, verified: true, createdAt: "2024-02-03" },
  { id: "r3", toolId: "t2", userName: "Emily Watson", userAvatar: "EW", rating: 5, title: "Best AI art generator", content: "Nothing comes close to Midjourney's artistic quality. The V6 model produces stunning images with incredible detail. The style reference feature is a game-changer for maintaining consistency.", helpfulCount: 189, verified: true, createdAt: "2024-01-22" },
  { id: "r4", toolId: "t3", userName: "David Kim", userAvatar: "DK", rating: 5, title: "Best AI for long documents", content: "Claude's 200K context window is unmatched. I can upload entire books and have intelligent conversations about them. The writing quality is more nuanced than competitors.", helpfulCount: 142, verified: true, createdAt: "2024-02-14" },
  { id: "r5", toolId: "t4", userName: "Lisa Park", userAvatar: "LP", rating: 4, title: "Saves hours every day", content: "Copilot has become an essential part of my workflow. The completions are spot-on most of the time, and the chat feature helps me understand unfamiliar codebases quickly.", helpfulCount: 98, verified: true, createdAt: "2024-01-08" },
  { id: "r6", toolId: "t7", userName: "Alex Turner", userAvatar: "AT", rating: 5, title: "Revolutionary voice cloning", content: "The voice cloning quality is scary good. I cloned my own voice in 30 seconds and it sounds indistinguishable from the original. Great for content creators.", helpfulCount: 167, verified: true, createdAt: "2024-02-20" },
];

export type Testimonial = {
  id: string;
  name: string;
  role: string;
  company: string;
  avatar: string;
  content: string;
  rating: number;
};

export const TESTIMONIALS: Testimonial[] = [
  { id: "tm1", name: "Jennifer Hayes", role: "Product Manager", company: "TechFlow", avatar: "JH", content: "AIToolsHub has become our team's go-to resource for discovering new AI tools. The comparison feature alone saves us hours of research every week.", rating: 5 },
  { id: "tm2", name: "Raj Patel", role: "CTO", company: "StartupX", avatar: "RP", content: "The directory is incredibly comprehensive. We've found 3 tools through AIToolsHub that have transformed our development workflow.", rating: 5 },
  { id: "tm3", name: "Maria Garcia", role: "Marketing Director", company: "GrowthLabs", avatar: "MG", content: "As a marketer, I love how easy it is to find and compare AI tools for different use cases. The sponsored listings are actually relevant, not spammy.", rating: 5 },
  { id: "tm4", name: "Tom Anderson", role: "Indie Developer", company: "SoloBuilds", avatar: "TA", content: "The API access lets me integrate tool data directly into my own app. Documentation is excellent and the rate limits are generous.", rating: 5 },
];

export type BlogPost = {
  id: string;
  slug: string;
  title: string;
  excerpt: string;
  content: string;
  author: string;
  authorAvatar: string;
  publishedAt: string;
  readTime: string;
  category: string;
  coverGradient: string;
};

export const BLOG_POSTS: BlogPost[] = [
  { id: "b1", slug: "best-ai-tools-2024", title: "The 25 Best AI Tools of 2024: A Complete Guide", excerpt: "From content creation to coding, we've tested and ranked the most powerful AI tools that are transforming workflows this year.", content: "Full article content...", author: "Sarah Mitchell", authorAvatar: "SM", publishedAt: "2024-03-15", readTime: "12 min", category: "Guides", coverGradient: "from-violet-500 to-purple-500" },
  { id: "b2", slug: "ai-image-generation-comparison", title: "Midjourney vs DALL-E vs Stable Diffusion: Which Wins in 2024?", excerpt: "We put the top three AI image generators head-to-head across 10 categories. The results might surprise you.", content: "Full article content...", author: "James Lee", authorAvatar: "JL", publishedAt: "2024-03-12", readTime: "8 min", category: "Comparisons", coverGradient: "from-pink-500 to-rose-500" },
  { id: "b3", slug: "ai-coding-assistants", title: "How AI Coding Assistants Are Revolutionizing Software Development", excerpt: "GitHub Copilot, Cursor, and Codeium are changing how developers write code. Here's what you need to know.", content: "Full article content...", author: "Priya Sharma", authorAvatar: "PS", publishedAt: "2024-03-10", readTime: "10 min", category: "Development", coverGradient: "from-emerald-500 to-teal-500" },
];

// ---------------------------------------------------------------------
// i18n STRINGS — 5 languages with full RTL support for Arabic
// ---------------------------------------------------------------------

export type Locale = "en" | "ar" | "es" | "zh" | "hi";

export const LOCALES: { code: Locale; name: string; nativeName: string; flag: string; rtl?: boolean }[] = [
  { code: "en", name: "English", nativeName: "English", flag: "🇬🇧" },
  { code: "ar", name: "Arabic", nativeName: "العربية", flag: "🇸🇦", rtl: true },
  { code: "es", name: "Spanish", nativeName: "Español", flag: "🇪🇸" },
  { code: "zh", name: "Chinese", nativeName: "中文", flag: "🇨🇳" },
  { code: "hi", name: "Hindi", nativeName: "हिन्दी", flag: "🇮🇳" },
];

export const I18N: Record<Locale, Record<string, string>> = {
  en: {
    "nav.discover": "Discover",
    "nav.categories": "Categories",
    "nav.compare": "Compare",
    "nav.pricing": "Pricing",
    "nav.blog": "Blog",
    "nav.api": "API Docs",
    "nav.signIn": "Sign In",
    "nav.signUp": "Get Started",
    "nav.dashboard": "Dashboard",
    "hero.badge": "Trusted by 2M+ creators worldwide",
    "hero.title": "Discover the Best AI Tools, Curated & Ranked",
    "hero.subtitle": "Explore 100,000+ AI tools across 50+ categories. Compare features, read verified reviews, and find the perfect AI solution for your workflow.",
    "hero.searchPlaceholder": "Search for AI tools, categories, or use cases...",
    "hero.searchButton": "Search",
    "hero.aiSearchHint": "Try: \"AI for writing marketing copy\"",
    "stats.tools": "AI Tools",
    "stats.categories": "Categories",
    "stats.users": "Monthly Users",
    "stats.reviews": "Reviews",
    "categories.title": "Browse by Category",
    "categories.subtitle": "Find the perfect AI tools for any use case",
    "categories.viewAll": "View all categories",
    "featured.title": "Featured AI Tools",
    "featured.subtitle": "Hand-picked tools our community loves this week",
    "featured.viewAll": "View all tools",
    "directory.title": "Explore the Directory",
    "directory.subtitle": "Filter, search, and discover AI tools that match your needs",
    "directory.results": "tools found",
    "directory.filters": "Filters",
    "directory.sortBy": "Sort by",
    "directory.category": "Category",
    "directory.pricing": "Pricing",
    "directory.rating": "Rating",
    "directory.sort.popular": "Most Popular",
    "directory.sort.rated": "Highest Rated",
    "directory.sort.newest": "Newest",
    "directory.sort.priceLow": "Price: Low to High",
    "directory.sort.priceHigh": "Price: High to Low",
    "directory.empty": "No tools match your filters. Try adjusting your search.",
    "directory.clearFilters": "Clear all filters",
    "directory.loadMore": "Load more tools",
    "pricing.free": "Free",
    "pricing.freemium": "Freemium",
    "pricing.paid": "Paid",
    "pricing.freeTrial": "Free Trial",
    "pricing.contactPricing": "Contact for Pricing",
    "pricing.perMonth": "/mo",
    "pricing.perYear": "/yr",
    "pricing.title": "Simple, Transparent Pricing",
    "pricing.subtitle": "Choose the plan that fits your needs. Cancel anytime.",
    "pricing.monthly": "Monthly",
    "pricing.yearly": "Yearly",
    "pricing.save": "Save 20%",
    "pricing.popular": "Most Popular",
    "pricing.cta.free": "Get Started Free",
    "pricing.cta.pro": "Start Pro Trial",
    "pricing.cta.business": "Start Business Trial",
    "pricing.cta.enterprise": "Contact Sales",
    "pricing.cta.currentPlan": "Current Plan",
    "compare.title": "Compare AI Tools Side by Side",
    "compare.subtitle": "Add tools to compare features, pricing, and ratings",
    "compare.addButton": "Add tool to compare",
    "compare.remove": "Remove",
    "compare.clearAll": "Clear all",
    "compare.empty": "Add at least 2 tools to start comparing",
    "compare.feature": "Feature",
    "compare.pricing": "Pricing",
    "compare.rating": "Rating",
    "compare.reviews": "Reviews",
    "compare.category": "Category",
    "compare.tags": "Tags",
    "compare.website": "Website",
    "compare.addedAt": "Added",
    "userDashboard.title": "Your Dashboard",
    "userDashboard.subtitle": "Manage your bookmarks, collections, and reviews",
    "userDashboard.overview": "Overview",
    "userDashboard.bookmarks": "Bookmarks",
    "userDashboard.collections": "Collections",
    "userDashboard.reviews": "Reviews",
    "userDashboard.analytics": "Analytics",
    "userDashboard.totalBookmarks": "Total Bookmarks",
    "userDashboard.totalCollections": "Collections",
    "userDashboard.totalReviews": "Reviews Written",
    "userDashboard.recentActivity": "Recent Activity",
    "adminDashboard.title": "Admin Dashboard",
    "adminDashboard.subtitle": "Manage tools, users, and platform analytics",
    "adminDashboard.tools": "Tools",
    "adminDashboard.analytics": "Analytics",
    "adminDashboard.moderation": "Moderation",
    "adminDashboard.users": "Users",
    "adminDashboard.auditLogs": "Audit Logs",
    "adminDashboard.totalTools": "Total Tools",
    "adminDashboard.totalUsers": "Total Users",
    "adminDashboard.mrr": "Monthly Revenue",
    "adminDashboard.pendingReviews": "Pending Reviews",
    "cta.title": "Ready to Transform Your Workflow?",
    "cta.subtitle": "Join 2M+ creators, developers, and businesses using AIToolsHub to find their perfect AI stack.",
    "cta.button": "Start Free Today",
    "footer.about": "About",
    "footer.product": "Product",
    "footer.resources": "Resources",
    "footer.legal": "Legal",
    "footer.company": "Company",
    "footer.rights": "All rights reserved.",
    "footer.madeWith": "Made with",
    "footer.forCreators": "for creators",
    "common.viewDetails": "View Details",
    "common.visit": "Visit Website",
    "common.bookmark": "Bookmark",
    "common.bookmarked": "Bookmarked",
    "common.share": "Share",
    "common.compare": "Compare",
    "common.added": "Added",
    "common.free": "FREE",
    "common.features": "Features",
    "common.pricing": "Pricing",
    "common.reviews": "Reviews",
    "common.alternatives": "Alternatives",
    "common.screenshots": "Screenshots",
    "common.verified": "Verified",
    "common.sponsored": "Sponsored",
    "common.featured": "Featured",
    "common.search": "Search",
    "common.close": "Close",
    "common.apply": "Apply",
    "common.cancel": "Cancel",
    "common.all": "All",
  },
  ar: {
    "nav.discover": "اكتشف",
    "nav.categories": "الفئات",
    "nav.compare": "قارن",
    "nav.pricing": "الأسعار",
    "nav.blog": "المدونة",
    "nav.api": "وثائق API",
    "nav.signIn": "تسجيل الدخول",
    "nav.signUp": "ابدأ الآن",
    "nav.dashboard": "لوحة التحكم",
    "hero.badge": "موثوق به من قبل أكثر من 2 مليون مبدع حول العالم",
    "hero.title": "اكتشف أفضل أدوات الذكاء الاصطناعي، منسقة ومرتبة",
    "hero.subtitle": "استكشف أكثر من 100,000 أداة ذكاء اصطناعي في أكثر من 50 فئة. قارن الميزات، واقرأ المراجعات الموثقة، واعثر على حل الذكاء الاصطناعي المثالي لسير عملك.",
    "hero.searchPlaceholder": "ابحث عن أدوات الذكاء الاصطناعي أو الفئات أو حالات الاستخدام...",
    "hero.searchButton": "بحث",
    "hero.aiSearchHint": "جرب: \"الذكاء الاصطناعي لكتابة المحتوى التسويقي\"",
    "stats.tools": "أداة ذكاء اصطناعي",
    "stats.categories": "فئة",
    "stats.users": "مستخدم شهرياً",
    "stats.reviews": "مراجعة",
    "categories.title": "تصفح حسب الفئة",
    "categories.subtitle": "اعثر على أدوات الذكاء الاصطناعي المثالية لأي حالة استخدام",
    "categories.viewAll": "عرض جميع الفئات",
    "featured.title": "أدوات الذكاء الاصطناعي المميزة",
    "featured.subtitle": "أدوات مختارة يدوياً يحبها مجتمعنا هذا الأسبوع",
    "featured.viewAll": "عرض جميع الأدوات",
    "directory.title": "استكشف الدليل",
    "directory.subtitle": "قم بالتصفية والبحث واكتشف أدوات الذكاء الاصطناعي التي تناسب احتياجاتك",
    "directory.results": "أداة موجودة",
    "directory.filters": "المرشحات",
    "directory.sortBy": "ترتيب حسب",
    "directory.category": "الفئة",
    "directory.pricing": "الأسعار",
    "directory.rating": "التقييم",
    "directory.sort.popular": "الأكثر شعبية",
    "directory.sort.rated": "الأعلى تقييماً",
    "directory.sort.newest": "الأحدث",
    "directory.sort.priceLow": "السعر: من الأقل إلى الأعلى",
    "directory.sort.priceHigh": "السعر: من الأعلى إلى الأقل",
    "directory.empty": "لا توجد أدوات تطابق مرشحاتك. حاول تعديل البحث.",
    "directory.clearFilters": "مسح جميع المرشحات",
    "directory.loadMore": "تحميل المزيد من الأدوات",
    "pricing.free": "مجاني",
    "pricing.freemium": "مجاني جزئياً",
    "pricing.paid": "مدفوع",
    "pricing.freeTrial": "تجربة مجانية",
    "pricing.contactPricing": "اتصل للتسعير",
    "pricing.perMonth": "/شهر",
    "pricing.perYear": "/سنة",
    "pricing.title": "أسعار بسيطة وشفافة",
    "pricing.subtitle": "اختر الخطة التي تناسب احتياجاتك. يمكنك الإلغاء في أي وقت.",
    "pricing.monthly": "شهري",
    "pricing.yearly": "سنوي",
    "pricing.save": "وفر 20%",
    "pricing.popular": "الأكثر شعبية",
    "pricing.cta.free": "ابدأ مجاناً",
    "pricing.cta.pro": "ابدأ تجربة Pro",
    "pricing.cta.business": "ابدأ تجربة الأعمال",
    "pricing.cta.enterprise": "اتصل بالمبيعات",
    "pricing.cta.currentPlan": "الخطة الحالية",
    "compare.title": "قارن أدوات الذكاء الاصطناعي جنباً إلى جنب",
    "compare.subtitle": "أضف أدوات للمقارنة بين الميزات والأسعار والتقييمات",
    "compare.addButton": "أضف أداة للمقارنة",
    "compare.remove": "إزالة",
    "compare.clearAll": "مسح الكل",
    "compare.empty": "أضف أداتين على الأقل لبدء المقارنة",
    "compare.feature": "الميزة",
    "compare.pricing": "الأسعار",
    "compare.rating": "التقييم",
    "compare.reviews": "المراجعات",
    "compare.category": "الفئة",
    "compare.tags": "العلامات",
    "compare.website": "الموقع",
    "compare.addedAt": "أضيفت في",
    "userDashboard.title": "لوحة التحكم الخاصة بك",
    "userDashboard.subtitle": "إدارة الإشارات المرجعية والمجموعات والمراجعات",
    "userDashboard.overview": "نظرة عامة",
    "userDashboard.bookmarks": "الإشارات المرجعية",
    "userDashboard.collections": "المجموعات",
    "userDashboard.reviews": "المراجعات",
    "userDashboard.analytics": "التحليلات",
    "userDashboard.totalBookmarks": "إجمالي الإشارات المرجعية",
    "userDashboard.totalCollections": "المجموعات",
    "userDashboard.totalReviews": "المراجعات المكتوبة",
    "userDashboard.recentActivity": "النشاط الأخير",
    "adminDashboard.title": "لوحة تحكم المدير",
    "adminDashboard.subtitle": "إدارة الأدوات والمستخدمين وتحليلات المنصة",
    "adminDashboard.tools": "الأدوات",
    "adminDashboard.analytics": "التحليلات",
    "adminDashboard.moderation": "الإشراف",
    "adminDashboard.users": "المستخدمون",
    "adminDashboard.auditLogs": "سجلات التدقيق",
    "adminDashboard.totalTools": "إجمالي الأدوات",
    "adminDashboard.totalUsers": "إجمالي المستخدمين",
    "adminDashboard.mrr": "الإيرادات الشهرية",
    "adminDashboard.pendingReviews": "المراجعات المعلقة",
    "cta.title": "هل أنت مستعد لتحويل سير عملك؟",
    "cta.subtitle": "انضم إلى أكثر من 2 مليون مبدع ومطور وشركة يستخدمون AIToolsHub للعثور على مجموعة الذكاء الاصطناعي المثالية.",
    "cta.button": "ابدأ مجاناً اليوم",
    "footer.about": "حول",
    "footer.product": "المنتج",
    "footer.resources": "الموارد",
    "footer.legal": "قانوني",
    "footer.company": "الشركة",
    "footer.rights": "جميع الحقوق محفوظة.",
    "footer.madeWith": "صُنع بـ",
    "footer.forCreators": "للمبدعين",
    "common.viewDetails": "عرض التفاصيل",
    "common.visit": "زيارة الموقع",
    "common.bookmark": "إشارة مرجعية",
    "common.bookmarked": "محفوظ",
    "common.share": "مشاركة",
    "common.compare": "قارن",
    "common.added": "مُضاف",
    "common.free": "مجاني",
    "common.features": "الميزات",
    "common.pricing": "الأسعار",
    "common.reviews": "المراجعات",
    "common.alternatives": "البدائل",
    "common.screenshots": "لقطات الشاشة",
    "common.verified": "موثق",
    "common.sponsored": "مُموَّل",
    "common.featured": "مميز",
    "common.search": "بحث",
    "common.close": "إغلاق",
    "common.apply": "تطبيق",
    "common.cancel": "إلغاء",
    "common.all": "الكل",
  },
  es: {
    "nav.discover": "Descubrir",
    "nav.categories": "Categorías",
    "nav.compare": "Comparar",
    "nav.pricing": "Precios",
    "nav.blog": "Blog",
    "nav.api": "Docs API",
    "nav.signIn": "Iniciar Sesión",
    "nav.signUp": "Empezar",
    "nav.dashboard": "Panel",
    "hero.badge": "Con la confianza de más de 2M de creadores en todo el mundo",
    "hero.title": "Descubre las mejores herramientas de IA, curadas y clasificadas",
    "hero.subtitle": "Explora más de 100.000 herramientas de IA en más de 50 categorías. Compara características, lee reseñas verificadas y encuentra la solución de IA perfecta para tu flujo de trabajo.",
    "hero.searchPlaceholder": "Buscar herramientas de IA, categorías o casos de uso...",
    "hero.searchButton": "Buscar",
    "hero.aiSearchHint": "Prueba: \"IA para escribir copy de marketing\"",
    "stats.tools": "Herramientas de IA",
    "stats.categories": "Categorías",
    "stats.users": "Usuarios Mensuales",
    "stats.reviews": "Reseñas",
    "categories.title": "Explorar por Categoría",
    "categories.subtitle": "Encuentra las herramientas de IA perfectas para cualquier caso de uso",
    "categories.viewAll": "Ver todas las categorías",
    "featured.title": "Herramientas de IA Destacadas",
    "featured.subtitle": "Herramientas seleccionadas manualmente que nuestra comunidad ama esta semana",
    "featured.viewAll": "Ver todas las herramientas",
    "directory.title": "Explorar el Directorio",
    "directory.subtitle": "Filtra, busca y descubre herramientas de IA que se adapten a tus necesidades",
    "directory.results": "herramientas encontradas",
    "directory.filters": "Filtros",
    "directory.sortBy": "Ordenar por",
    "directory.category": "Categoría",
    "directory.pricing": "Precios",
    "directory.rating": "Calificación",
    "directory.sort.popular": "Más Populares",
    "directory.sort.rated": "Mejor Calificadas",
    "directory.sort.newest": "Más Recientes",
    "directory.sort.priceLow": "Precio: Bajo a Alto",
    "directory.sort.priceHigh": "Precio: Alto a Bajo",
    "directory.empty": "Ninguna herramienta coincide con tus filtros. Intenta ajustar tu búsqueda.",
    "directory.clearFilters": "Limpiar todos los filtros",
    "directory.loadMore": "Cargar más herramientas",
    "pricing.free": "Gratis",
    "pricing.freemium": "Freemium",
    "pricing.paid": "De Pago",
    "pricing.freeTrial": "Prueba Gratis",
    "pricing.contactPricing": "Contactar para Precios",
    "pricing.perMonth": "/mes",
    "pricing.perYear": "/año",
    "pricing.title": "Precios Simples y Transparentes",
    "pricing.subtitle": "Elige el plan que se adapte a tus necesidades. Cancela cuando quieras.",
    "pricing.monthly": "Mensual",
    "pricing.yearly": "Anual",
    "pricing.save": "Ahorra 20%",
    "pricing.popular": "Más Popular",
    "pricing.cta.free": "Empezar Gratis",
    "pricing.cta.pro": "Probar Pro",
    "pricing.cta.business": "Probar Business",
    "pricing.cta.enterprise": "Contactar Ventas",
    "pricing.cta.currentPlan": "Plan Actual",
    "compare.title": "Compara Herramientas de IA Lado a Lado",
    "compare.subtitle": "Añade herramientas para comparar características, precios y calificaciones",
    "compare.addButton": "Añadir herramienta para comparar",
    "compare.remove": "Quitar",
    "compare.clearAll": "Limpiar todo",
    "compare.empty": "Añade al menos 2 herramientas para empezar a comparar",
    "compare.feature": "Característica",
    "compare.pricing": "Precios",
    "compare.rating": "Calificación",
    "compare.reviews": "Reseñas",
    "compare.category": "Categoría",
    "compare.tags": "Etiquetas",
    "compare.website": "Sitio Web",
    "compare.addedAt": "Añadido",
    "userDashboard.title": "Tu Panel",
    "userDashboard.subtitle": "Administra tus favoritos, colecciones y reseñas",
    "userDashboard.overview": "Resumen",
    "userDashboard.bookmarks": "Favoritos",
    "userDashboard.collections": "Colecciones",
    "userDashboard.reviews": "Reseñas",
    "userDashboard.analytics": "Analíticas",
    "userDashboard.totalBookmarks": "Favoritos Totales",
    "userDashboard.totalCollections": "Colecciones",
    "userDashboard.totalReviews": "Reseñas Escritas",
    "userDashboard.recentActivity": "Actividad Reciente",
    "adminDashboard.title": "Panel de Administración",
    "adminDashboard.subtitle": "Administra herramientas, usuarios y analíticas de la plataforma",
    "adminDashboard.tools": "Herramientas",
    "adminDashboard.analytics": "Analíticas",
    "adminDashboard.moderation": "Moderación",
    "adminDashboard.users": "Usuarios",
    "adminDashboard.auditLogs": "Registros de Auditoría",
    "adminDashboard.totalTools": "Herramientas Totales",
    "adminDashboard.totalUsers": "Usuarios Totales",
    "adminDashboard.mrr": "Ingresos Mensuales",
    "adminDashboard.pendingReviews": "Reseñas Pendientes",
    "cta.title": "¿Listo para Transformar Tu Flujo de Trabajo?",
    "cta.subtitle": "Únete a más de 2M de creadores, desarrolladores y empresas que usan AIToolsHub para encontrar su stack de IA perfecto.",
    "cta.button": "Empezar Gratis Hoy",
    "footer.about": "Acerca de",
    "footer.product": "Producto",
    "footer.resources": "Recursos",
    "footer.legal": "Legal",
    "footer.company": "Empresa",
    "footer.rights": "Todos los derechos reservados.",
    "footer.madeWith": "Hecho con",
    "footer.forCreators": "para creadores",
    "common.viewDetails": "Ver Detalles",
    "common.visit": "Visitar Sitio",
    "common.bookmark": "Favorito",
    "common.bookmarked": "Guardado",
    "common.share": "Compartir",
    "common.compare": "Comparar",
    "common.added": "Añadido",
    "common.free": "GRATIS",
    "common.features": "Características",
    "common.pricing": "Precios",
    "common.reviews": "Reseñas",
    "common.alternatives": "Alternativas",
    "common.screenshots": "Capturas",
    "common.verified": "Verificado",
    "common.sponsored": "Patrocinado",
    "common.featured": "Destacado",
    "common.search": "Buscar",
    "common.close": "Cerrar",
    "common.apply": "Aplicar",
    "common.cancel": "Cancelar",
    "common.all": "Todos",
  },
  zh: {
    "nav.discover": "发现",
    "nav.categories": "分类",
    "nav.compare": "对比",
    "nav.pricing": "价格",
    "nav.blog": "博客",
    "nav.api": "API文档",
    "nav.signIn": "登录",
    "nav.signUp": "开始使用",
    "nav.dashboard": "控制台",
    "hero.badge": "全球超过200万创作者的信赖之选",
    "hero.title": "发现最好的AI工具，精心策划和排名",
    "hero.subtitle": "探索50多个分类中的10万多个AI工具。比较功能、阅读经过验证的评论，找到适合您工作流程的完美AI解决方案。",
    "hero.searchPlaceholder": "搜索AI工具、分类或用例...",
    "hero.searchButton": "搜索",
    "hero.aiSearchHint": "试试：\"用于撰写营销文案的AI\"",
    "stats.tools": "AI工具",
    "stats.categories": "分类",
    "stats.users": "月活用户",
    "stats.reviews": "评论",
    "categories.title": "按分类浏览",
    "categories.subtitle": "为任何用例找到完美的AI工具",
    "categories.viewAll": "查看所有分类",
    "featured.title": "精选AI工具",
    "featured.subtitle": "本周我们的社区喜爱的精选工具",
    "featured.viewAll": "查看所有工具",
    "directory.title": "探索目录",
    "directory.subtitle": "筛选、搜索并发现适合您需求的AI工具",
    "directory.results": "个工具",
    "directory.filters": "筛选器",
    "directory.sortBy": "排序方式",
    "directory.category": "分类",
    "directory.pricing": "价格",
    "directory.rating": "评分",
    "directory.sort.popular": "最热门",
    "directory.sort.rated": "评分最高",
    "directory.sort.newest": "最新",
    "directory.sort.priceLow": "价格：从低到高",
    "directory.sort.priceHigh": "价格：从高到低",
    "directory.empty": "没有工具匹配您的筛选条件。请尝试调整搜索。",
    "directory.clearFilters": "清除所有筛选器",
    "directory.loadMore": "加载更多工具",
    "pricing.free": "免费",
    "pricing.freemium": "免费增值",
    "pricing.paid": "付费",
    "pricing.freeTrial": "免费试用",
    "pricing.contactPricing": "联系获取报价",
    "pricing.perMonth": "/月",
    "pricing.perYear": "/年",
    "pricing.title": "简单透明的价格",
    "pricing.subtitle": "选择适合您需求的计划。随时取消。",
    "pricing.monthly": "月付",
    "pricing.yearly": "年付",
    "pricing.save": "节省20%",
    "pricing.popular": "最受欢迎",
    "pricing.cta.free": "免费开始",
    "pricing.cta.pro": "开始Pro试用",
    "pricing.cta.business": "开始商业试用",
    "pricing.cta.enterprise": "联系销售",
    "pricing.cta.currentPlan": "当前计划",
    "compare.title": "并排比较AI工具",
    "compare.subtitle": "添加工具以比较功能、价格和评分",
    "compare.addButton": "添加工具进行比较",
    "compare.remove": "移除",
    "compare.clearAll": "全部清除",
    "compare.empty": "至少添加2个工具才能开始比较",
    "compare.feature": "功能",
    "compare.pricing": "价格",
    "compare.rating": "评分",
    "compare.reviews": "评论",
    "compare.category": "分类",
    "compare.tags": "标签",
    "compare.website": "网站",
    "compare.addedAt": "添加于",
    "userDashboard.title": "您的控制台",
    "userDashboard.subtitle": "管理您的书签、收藏和评论",
    "userDashboard.overview": "概览",
    "userDashboard.bookmarks": "书签",
    "userDashboard.collections": "收藏",
    "userDashboard.reviews": "评论",
    "userDashboard.analytics": "分析",
    "userDashboard.totalBookmarks": "书签总数",
    "userDashboard.totalCollections": "收藏数",
    "userDashboard.totalReviews": "已写评论",
    "userDashboard.recentActivity": "最近活动",
    "adminDashboard.title": "管理控制台",
    "adminDashboard.subtitle": "管理工具、用户和平台分析",
    "adminDashboard.tools": "工具",
    "adminDashboard.analytics": "分析",
    "adminDashboard.moderation": "审核",
    "adminDashboard.users": "用户",
    "adminDashboard.auditLogs": "审计日志",
    "adminDashboard.totalTools": "工具总数",
    "adminDashboard.totalUsers": "用户总数",
    "adminDashboard.mrr": "月收入",
    "adminDashboard.pendingReviews": "待审评论",
    "cta.title": "准备好改变您的工作流程了吗？",
    "cta.subtitle": "加入200多万使用AIToolsHub找到完美AI技术栈的创作者、开发者和企业。",
    "cta.button": "今天免费开始",
    "footer.about": "关于",
    "footer.product": "产品",
    "footer.resources": "资源",
    "footer.legal": "法律",
    "footer.company": "公司",
    "footer.rights": "保留所有权利。",
    "footer.madeWith": "用心制作",
    "footer.forCreators": "为创作者",
    "common.viewDetails": "查看详情",
    "common.visit": "访问网站",
    "common.bookmark": "书签",
    "common.bookmarked": "已收藏",
    "common.share": "分享",
    "common.compare": "对比",
    "common.added": "已添加",
    "common.free": "免费",
    "common.features": "功能",
    "common.pricing": "价格",
    "common.reviews": "评论",
    "common.alternatives": "替代品",
    "common.screenshots": "截图",
    "common.verified": "已验证",
    "common.sponsored": "赞助",
    "common.featured": "精选",
    "common.search": "搜索",
    "common.close": "关闭",
    "common.apply": "应用",
    "common.cancel": "取消",
    "common.all": "全部",
  },
  hi: {
    "nav.discover": "खोजें",
    "nav.categories": "श्रेणियाँ",
    "nav.compare": "तुलना",
    "nav.pricing": "मूल्य",
    "nav.blog": "ब्लॉग",
    "nav.api": "API दस्तावेज़",
    "nav.signIn": "साइन इन",
    "nav.signUp": "शुरू करें",
    "nav.dashboard": "डैशबोर्ड",
    "hero.badge": "दुनिया भर में 2M+ रचनाकारों द्वारा भरोसा किया गया",
    "hero.title": "सर्वश्रेष्ठ AI टूल खोजें, चयनित और रैंक किए गए",
    "hero.subtitle": "50+ श्रेणियों में 100,000+ AI टूल एक्सप्लोर करें। विशेषताओं की तुलना करें, सत्यापित समीक्षाएँ पढ़ें, और अपने वर्कफ़्लो के लिए सही AI समाधान खोजें।",
    "hero.searchPlaceholder": "AI टूल, श्रेणियाँ, या उपयोग के मामले खोजें...",
    "hero.searchButton": "खोज",
    "hero.aiSearchHint": "आज़माएँ: \"मार्केटिंग कॉपी लिखने के लिए AI\"",
    "stats.tools": "AI टूल",
    "stats.categories": "श्रेणियाँ",
    "stats.users": "मासिक उपयोगकर्ता",
    "stats.reviews": "समीक्षाएँ",
    "categories.title": "श्रेणी द्वारा ब्राउज़ करें",
    "categories.subtitle": "किसी भी उपयोग के लिए सही AI टूल खोजें",
    "categories.viewAll": "सभी श्रेणियाँ देखें",
    "featured.title": "फ़ीचर्ड AI टूल",
    "featured.subtitle": "इस सप्ताह हमारे समुदाय द्वारा पसंद किए गए चुने हुए टूल",
    "featured.viewAll": "सभी टूल देखें",
    "directory.title": "डायरेक्टरी एक्सप्लोर करें",
    "directory.subtitle": "फ़िल्टर करें, खोजें, और अपनी ज़रूरतों से मेल खाने वाले AI टूल खोजें",
    "directory.results": "टूल मिले",
    "directory.filters": "फ़िल्टर",
    "directory.sortBy": "क्रमबद्ध करें",
    "directory.category": "श्रेणी",
    "directory.pricing": "मूल्य",
    "directory.rating": "रेटिंग",
    "directory.sort.popular": "सबसे लोकप्रिय",
    "directory.sort.rated": "उच्चतम रेटेड",
    "directory.sort.newest": "नवीनतम",
    "directory.sort.priceLow": "मूल्य: कम से अधिक",
    "directory.sort.priceHigh": "मूल्य: अधिक से कम",
    "directory.empty": "आपके फ़िल्टर से कोई टूल मेल नहीं खाता। अपनी खोज समायोजित करने का प्रयास करें।",
    "directory.clearFilters": "सभी फ़िल्टर साफ़ करें",
    "directory.loadMore": "और टूल लोड करें",
    "pricing.free": "मुफ़्त",
    "pricing.freemium": "फ्रीमियम",
    "pricing.paid": "सशुल्क",
    "pricing.freeTrial": "मुफ़्त परीक्षण",
    "pricing.contactPricing": "मूल्य के लिए संपर्क करें",
    "pricing.perMonth": "/माह",
    "pricing.perYear": "/वर्ष",
    "pricing.title": "सरल, पारदर्शी मूल्य निर्धारण",
    "pricing.subtitle": "अपनी ज़रूरतों के अनुसार योजना चुनें। कभी भी रद्द करें।",
    "pricing.monthly": "मासिक",
    "pricing.yearly": "वार्षिक",
    "pricing.save": "20% बचाएँ",
    "pricing.popular": "सबसे लोकप्रिय",
    "pricing.cta.free": "मुफ़्त शुरू करें",
    "pricing.cta.pro": "Pro परीक्षण शुरू करें",
    "pricing.cta.business": "बिज़नेस परीक्षण शुरू करें",
    "pricing.cta.enterprise": "बिक्री से संपर्क करें",
    "pricing.cta.currentPlan": "वर्तमान योजना",
    "compare.title": "AI टूल की आमने-सामने तुलना करें",
    "compare.subtitle": "विशेषताओं, मूल्य और रेटिंग की तुलना के लिए टूल जोड़ें",
    "compare.addButton": "तुलना के लिए टूल जोड़ें",
    "compare.remove": "हटाएँ",
    "compare.clearAll": "सभी साफ़ करें",
    "compare.empty": "तुलना शुरू करने के लिए कम से कम 2 टूल जोड़ें",
    "compare.feature": "विशेषता",
    "compare.pricing": "मूल्य",
    "compare.rating": "रेटिंग",
    "compare.reviews": "समीक्षाएँ",
    "compare.category": "श्रेणी",
    "compare.tags": "टैग",
    "compare.website": "वेबसाइट",
    "compare.addedAt": "जोड़ा गया",
    "userDashboard.title": "आपका डैशबोर्ड",
    "userDashboard.subtitle": "अपने बुकमार्क, संग्रह और समीक्षाएँ प्रबंधित करें",
    "userDashboard.overview": "अवलोकन",
    "userDashboard.bookmarks": "बुकमार्क",
    "userDashboard.collections": "संग्रह",
    "userDashboard.reviews": "समीक्षाएँ",
    "userDashboard.analytics": "एनालिटिक्स",
    "userDashboard.totalBookmarks": "कुल बुकमार्क",
    "userDashboard.totalCollections": "संग्रह",
    "userDashboard.totalReviews": "लिखी गई समीक्षाएँ",
    "userDashboard.recentActivity": "हाल की गतिविधि",
    "adminDashboard.title": "एडमिन डैशबोर्ड",
    "adminDashboard.subtitle": "टूल, उपयोगकर्ता और प्लेटफ़ॉर्म एनालिटिक्स प्रबंधित करें",
    "adminDashboard.tools": "टूल",
    "adminDashboard.analytics": "एनालिटिक्स",
    "adminDashboard.moderation": "मॉडरेशन",
    "adminDashboard.users": "उपयोगकर्ता",
    "adminDashboard.auditLogs": "ऑडिट लॉग",
    "adminDashboard.totalTools": "कुल टूल",
    "adminDashboard.totalUsers": "कुल उपयोगकर्ता",
    "adminDashboard.mrr": "मासिक राजस्व",
    "adminDashboard.pendingReviews": "लंबित समीक्षाएँ",
    "cta.title": "अपने वर्कफ़्लो को बदलने के लिए तैयार हैं?",
    "cta.subtitle": "AIToolsHub का उपयोग करके अपने परफेक्ट AI स्टैक को खोजने वाले 2M+ रचनाकारों, डेवलपर्स और व्यवसायों में शामिल हों।",
    "cta.button": "आज मुफ़्त शुरू करें",
    "footer.about": "के बारे में",
    "footer.product": "उत्पाद",
    "footer.resources": "संसाधन",
    "footer.legal": "कानूनी",
    "footer.company": "कंपनी",
    "footer.rights": "सर्वाधिकार सुरक्षित।",
    "footer.madeWith": "के साथ बनाया गया",
    "footer.forCreators": "रचनाकारों के लिए",
    "common.viewDetails": "विवरण देखें",
    "common.visit": "वेबसाइट पर जाएँ",
    "common.bookmark": "बुकमार्क",
    "common.bookmarked": "बुकमार्क किया गया",
    "common.share": "साझा करें",
    "common.compare": "तुलना",
    "common.added": "जोड़ा गया",
    "common.free": "मुफ़्त",
    "common.features": "विशेषताएँ",
    "common.pricing": "मूल्य",
    "common.reviews": "समीक्षाएँ",
    "common.alternatives": "विकल्प",
    "common.screenshots": "स्क्रीनशॉट",
    "common.verified": "सत्यापित",
    "common.sponsored": "प्रायोजित",
    "common.featured": "फ़ीचर्ड",
    "common.search": "खोज",
    "common.close": "बंद करें",
    "common.apply": "लागू करें",
    "common.cancel": "रद्द करें",
    "common.all": "सभी",
  },
};
