// =====================================================================
// Centralized mock data for AI Tools Directory
// Used both at runtime (no DB needed) and for seeding
// =====================================================================

export type Tool = {
  id: string;
  slug: string;
  name: string;
  tagline: string;
  description: string;
  longDescription: string;
  websiteUrl: string;
  affiliateUrl?: string; // Affiliate link (overrides websiteUrl when present)
  logoUrl: string;
  bannerUrl?: string;
  pricingType: "FREE" | "FREEMIUM" | "PAID" | "FREE_TRIAL" | "CONTACT_PRICING";
  startingPrice?: number;
  currency: string;
  freeTrial: boolean;
  freeTrialDays?: number;
  rating: number;
  reviewCount: number;
  viewCount: number;
  clickCount: number;
  bookmarkCount: number;
  featured: boolean;
  sponsored: boolean;
  verified: boolean;
  launchedAt: string;
  categorySlug: string;
  tags: string[];
  features: string[];
  pricingPlans: {
    name: string;
    price: number;
    period: "MONTHLY" | "YEARLY" | "ONE_TIME";
    features: string[];
    isPopular?: boolean;
  }[];
};

export type Category = {
  id: string;
  slug: string;
  name: string;
  description: string;
  icon: string;
  color: string;
  toolCount: number;
  isFeatured: boolean;
};

export const CATEGORIES: Category[] = [
  { id: "c1", slug: "writing", name: "Writing & Content", description: "AI tools for writing, copywriting, and content creation", icon: "PenLine", color: "violet", toolCount: 1842, isFeatured: true },
  { id: "c2", slug: "image", name: "Image Generation", description: "Generate, edit, and enhance images with AI", icon: "ImageIcon", color: "pink", toolCount: 1267, isFeatured: true },
  { id: "c3", slug: "video", name: "Video & Animation", description: "Create, edit, and animate videos with AI", icon: "Video", color: "rose", toolCount: 893, isFeatured: true },
  { id: "c4", slug: "code", name: "Code & Development", description: "AI coding assistants, code generation, dev tools", icon: "Code2", color: "emerald", toolCount: 1456, isFeatured: true },
  { id: "c5", slug: "chat", name: "Chatbots & Assistants", description: "Conversational AI, virtual assistants, chatbots", icon: "MessageSquare", color: "blue", toolCount: 2104, isFeatured: true },
  { id: "c6", slug: "audio", name: "Audio & Music", description: "Voice synthesis, music generation, audio editing", icon: "Music", color: "amber", toolCount: 678, isFeatured: true },
  { id: "c7", slug: "productivity", name: "Productivity", description: "AI tools to boost your personal and team productivity", icon: "Zap", color: "orange", toolCount: 1934, isFeatured: true },
  { id: "c8", slug: "marketing", name: "Marketing & SEO", description: "AI for marketing automation, SEO, and growth", icon: "TrendingUp", color: "green", toolCount: 1123, isFeatured: true },
  { id: "c9", slug: "design", name: "Design & UX", description: "AI-powered design tools, UI/UX, branding", icon: "Palette", color: "purple", toolCount: 987, isFeatured: true },
  { id: "c10", slug: "data", name: "Data & Analytics", description: "AI for data analysis, visualization, and insights", icon: "BarChart3", color: "cyan", toolCount: 743, isFeatured: true },
  { id: "c11", slug: "research", name: "Research & Education", description: "AI tools for learning, research, and academia", icon: "GraduationCap", color: "teal", toolCount: 654, isFeatured: false },
  { id: "c12", slug: "business", name: "Business & Operations", description: "AI for HR, finance, ops, and enterprise workflows", icon: "Briefcase", color: "slate", toolCount: 1289, isFeatured: false },
];

const ICON_BASE = "https://api.dicebear.com/7.x/shapes/svg?seed=";

export const TOOLS: Tool[] = [
  {
    id: "t1",
    slug: "chatgpt",
    name: "ChatGPT",
    tagline: "Conversational AI assistant by OpenAI",
    description: "Advanced AI chatbot capable of natural conversations, code generation, analysis, and more.",
    longDescription: "ChatGPT is a leading conversational AI developed by OpenAI. It can engage in natural language conversations, answer questions, write and debug code, draft content, analyze data, and perform a wide range of tasks. Powered by GPT-4, it supports multimodal input including text, images, and voice.",
    websiteUrl: "https://chat.openai.com",
    logoUrl: "https://api.dicebear.com/7.x/shapes/svg?seed=chatgpt&backgroundColor=10a37f",
    pricingType: "FREEMIUM",
    startingPrice: 20,
    currency: "USD",
    freeTrial: true,
    rating: 4.8,
    reviewCount: 12453,
    viewCount: 8942341,
    clickCount: 2341892,
    bookmarkCount: 89234,
    featured: true,
    sponsored: false,
    verified: true,
    launchedAt: "2022-11-30",
    categorySlug: "chat",
    tags: ["OpenAI", "GPT-4", "Assistant", "Multimodal"],
    features: ["GPT-4 Turbo", "Code Interpreter", "Web Browsing", "DALL-E Integration", "Voice Mode", "Custom GPTs", "Plugin Ecosystem"],
    pricingPlans: [
      { name: "Free", price: 0, period: "MONTHLY", features: ["GPT-3.5 access", "Standard response time", "Limited messages"] },
      { name: "Plus", price: 20, period: "MONTHLY", features: ["GPT-4 access", "Faster response time", "GPT-4 Turbo", "DALL-E", "Code Interpreter", "Web Browsing"], isPopular: true },
      { name: "Team", price: 25, period: "MONTHLY", features: ["Higher message limits", "Shared workspace", "Admin console", "Priority support"] },
    ],
  },
  {
    id: "t2",
    slug: "midjourney",
    name: "Midjourney",
    tagline: "AI image generation with artistic flair",
    description: "Create stunning AI-generated artwork from text prompts with unique artistic styles.",
    longDescription: "Midjourney is an independent research lab that produces a proprietary artificial intelligence program that creates images from textual descriptions. Known for its distinctive artistic style, Midjourney excels at creating highly stylized, painterly images that have a unique aesthetic appeal.",
    websiteUrl: "https://midjourney.com",
    logoUrl: "https://api.dicebear.com/7.x/shapes/svg?seed=midjourney&backgroundColor=4d4d4d",
    pricingType: "PAID",
    startingPrice: 10,
    currency: "USD",
    freeTrial: false,
    rating: 4.7,
    reviewCount: 8923,
    viewCount: 5621893,
    clickCount: 1782341,
    bookmarkCount: 67123,
    featured: true,
    sponsored: false,
    verified: true,
    launchedAt: "2022-07-12",
    categorySlug: "image",
    tags: ["AI Art", "Image Generation", "Discord"],
    features: ["V6 Model", "Style References", "Character References", "Variations", "Upscaling", "Pan & Zoom", "Remix Mode"],
    pricingPlans: [
      { name: "Basic", price: 10, period: "MONTHLY", features: ["3.3 hours of GPU time", "Commercial terms", "Web interface access"] },
      { name: "Standard", price: 30, period: "MONTHLY", features: ["15 hours of GPU time", "Unlimited relaxed generations", "Commercial terms"], isPopular: true },
      { name: "Pro", price: 60, period: "MONTHLY", features: ["30 hours of GPU time", "Unlimited relaxed generations", "Stealth mode", "12 priority image generations"] },
    ],
  },
  {
    id: "t3",
    slug: "claude",
    name: "Claude",
    tagline: "AI assistant by Anthropic",
    description: "Helpful, harmless, and honest AI assistant for writing, analysis, and coding.",
    longDescription: "Claude is a next-generation AI assistant built by Anthropic. It is designed to be helpful, harmless, and honest. Claude can handle a wide variety of tasks including writing, analysis, coding, math, and creative work. It features a 200K token context window and excels at following complex instructions.",
    websiteUrl: "https://claude.ai",
    logoUrl: "https://api.dicebear.com/7.x/shapes/svg?seed=claude&backgroundColor=d97757",
    pricingType: "FREEMIUM",
    startingPrice: 20,
    currency: "USD",
    freeTrial: true,
    rating: 4.9,
    reviewCount: 5234,
    viewCount: 3412893,
    clickCount: 923481,
    bookmarkCount: 45213,
    featured: true,
    sponsored: false,
    verified: true,
    launchedAt: "2023-03-14",
    categorySlug: "chat",
    tags: ["Anthropic", "Claude 3", "Long Context", "Analysis"],
    features: ["200K Context Window", "Claude 3 Opus", "Claude 3 Sonnet", "Claude 3 Haiku", "Vision Capabilities", "Tool Use", "Artifacts"],
    pricingPlans: [
      { name: "Free", price: 0, period: "MONTHLY", features: ["Claude 3.5 Sonnet access", "Daily message limit", "Standard response time"] },
      { name: "Pro", price: 20, period: "MONTHLY", features: ["5x more usage", "Priority access", "Claude 3 Opus", "Early access to features"], isPopular: true },
      { name: "Team", price: 30, period: "MONTHLY", features: ["Higher usage limits", "Team workspace", "Admin tools", "Billing consolidation"] },
    ],
  },
  {
    id: "t4",
    slug: "github-copilot",
    name: "GitHub Copilot",
    tagline: "Your AI pair programmer",
    description: "AI-powered code completion and generation directly in your editor.",
    longDescription: "GitHub Copilot uses the OpenAI Codex to suggest code and functions in real-time as you type. It integrates seamlessly with popular IDEs like VS Code, Visual Studio, Neovim, and JetBrains. Copilot helps developers write code faster, learn new languages, and reduce repetitive tasks.",
    websiteUrl: "https://github.com/features/copilot",
    logoUrl: "https://api.dicebear.com/7.x/shapes/svg?seed=copilot&backgroundColor=24292e",
    pricingType: "PAID",
    startingPrice: 10,
    currency: "USD",
    freeTrial: true,
    freeTrialDays: 30,
    rating: 4.6,
    reviewCount: 6789,
    viewCount: 4231892,
    clickCount: 1234892,
    bookmarkCount: 52341,
    featured: true,
    sponsored: false,
    verified: true,
    launchedAt: "2021-06-29",
    categorySlug: "code",
    tags: ["GitHub", "OpenAI", "Code Completion", "IDE"],
    features: ["Code Completion", "Copilot Chat", "PR Summaries", "Copilot CLI", "Multi-language Support", "Test Generation", "Code Translation"],
    pricingPlans: [
      { name: "Individual", price: 10, period: "MONTHLY", features: ["Code completions", "Copilot Chat", "IDE integration"] },
      { name: "Business", price: 19, period: "MONTHLY", features: ["Everything in Individual", "Organization policy management", "Audit logs", "IP indemnity"], isPopular: true },
      { name: "Enterprise", price: 39, period: "MONTHLY", features: ["Everything in Business", "Custom models", "Enterprise security", "Pull request summaries"] },
    ],
  },
  {
    id: "t5",
    slug: "runway",
    name: "Runway",
    tagline: "AI video generation and editing",
    description: "Create stunning videos with text-to-video, image-to-video, and AI editing tools.",
    longDescription: "Runway is an applied AI research company building tools for content creation. Their Gen-2 model can generate videos from text prompts, transform images into videos, and apply various AI-powered video editing effects. Runway is used by filmmakers, designers, and creators worldwide.",
    websiteUrl: "https://runwayml.com",
    logoUrl: "https://api.dicebear.com/7.x/shapes/svg?seed=runway&backgroundColor=000000",
    pricingType: "FREEMIUM",
    startingPrice: 15,
    currency: "USD",
    freeTrial: true,
    rating: 4.5,
    reviewCount: 3421,
    viewCount: 2341892,
    clickCount: 623481,
    bookmarkCount: 34213,
    featured: true,
    sponsored: true,
    verified: true,
    launchedAt: "2020-12-15",
    categorySlug: "video",
    tags: ["Video Generation", "Gen-2", "AI Editing"],
    features: ["Gen-2 Text-to-Video", "Image-to-Video", "Video-to-Video", "Motion Brush", "Camera Controls", "Inpainting", "Green Screen"],
    pricingPlans: [
      { name: "Free", price: 0, period: "MONTHLY", features: ["3 projects", "125 credits", "Watermarked exports"] },
      { name: "Standard", price: 15, period: "MONTHLY", features: ["Unlimited projects", "625 credits/month", "No watermark"], isPopular: true },
      { name: "Pro", price: 35, period: "MONTHLY", features: ["Everything in Standard", "2250 credits/month", "16K upscales", "Premium support"] },
    ],
  },
  {
    id: "t6",
    slug: "jasper",
    name: "Jasper",
    tagline: "AI content platform for marketing teams",
    description: "Enterprise-grade AI writing assistant for marketing and content creation.",
    longDescription: "Jasper is an AI content platform that helps marketing teams create on-brand content at scale. It offers templates for blogs, ads, emails, and more, with features like brand voice, SEO mode, and team collaboration. Trusted by 70,000+ teams worldwide.",
    websiteUrl: "https://jasper.ai",
    logoUrl: "https://api.dicebear.com/7.x/shapes/svg?seed=jasper&backgroundColor=8b5cf6",
    pricingType: "PAID",
    startingPrice: 39,
    currency: "USD",
    freeTrial: true,
    freeTrialDays: 7,
    rating: 4.4,
    reviewCount: 4521,
    viewCount: 1842934,
    clickCount: 523481,
    bookmarkCount: 28413,
    featured: false,
    sponsored: true,
    verified: true,
    launchedAt: "2021-01-20",
    categorySlug: "writing",
    tags: ["Marketing", "Copywriting", "Brand Voice"],
    features: ["Brand Voice", "50+ Templates", "SEO Mode", "Team Collaboration", "Campaigns", "Browser Extension", "API Access"],
    pricingPlans: [
      { name: "Creator", price: 39, period: "MONTHLY", features: ["1 brand voice", "50+ templates", "Browser extension"] },
      { name: "Pro", price: 59, period: "MONTHLY", features: ["3 brand voices", "SEO mode", "Campaigns", "API access"], isPopular: true },
      { name: "Business", price: 499, period: "MONTHLY", features: ["Custom brand voices", "SSO", "Custom templates", "Dedicated success manager"] },
    ],
  },
  {
    id: "t7",
    slug: "elevenlabs",
    name: "ElevenLabs",
    tagline: "Realistic AI voice generation",
    description: "Generate lifelike voices, clone voices, and create audio content with AI.",
    longDescription: "ElevenLabs is the leading AI voice generator and text-to-speech platform. It can generate highly realistic voices in 29 languages, clone voices from short samples, and create natural-sounding audio content. Used by audiobook publishers, game developers, and content creators.",
    websiteUrl: "https://elevenlabs.io",
    logoUrl: "https://api.dicebear.com/7.x/shapes/svg?seed=eleven&backgroundColor=000000",
    pricingType: "FREEMIUM",
    startingPrice: 5,
    currency: "USD",
    freeTrial: true,
    rating: 4.7,
    reviewCount: 2841,
    viewCount: 1234892,
    clickCount: 423481,
    bookmarkCount: 23421,
    featured: true,
    sponsored: false,
    verified: true,
    launchedAt: "2022-01-23",
    categorySlug: "audio",
    tags: ["Voice Cloning", "TTS", "Multilingual"],
    features: ["Text-to-Speech", "Voice Cloning", "29 Languages", "Sound Effects", "AI Dubbing", "Voice Library", "Studio Editor"],
    pricingPlans: [
      { name: "Free", price: 0, period: "MONTHLY", features: ["10K credits/month", "Commercial license", "Voice library access"] },
      { name: "Starter", price: 5, period: "MONTHLY", features: ["30K credits/month", "Voice cloning", "Audio projects"], isPopular: true },
      { name: "Creator", price: 22, period: "MONTHLY", features: ["100K credits/month", "Professional voice cloning", "Projects API"] },
    ],
  },
  {
    id: "t8",
    slug: "perplexity",
    name: "Perplexity",
    tagline: "AI-powered answer engine",
    description: "Get accurate, cited answers to any question with real-time web search.",
    longDescription: "Perplexity is an AI-powered answer engine that provides accurate, real-time information with citations. It combines the power of large language models with live web search to deliver trustworthy answers. Features include Copilot mode, file uploads, and focused search collections.",
    websiteUrl: "https://perplexity.ai",
    logoUrl: "https://api.dicebear.com/7.x/shapes/svg?seed=perplexity&backgroundColor=1fb8cd",
    pricingType: "FREEMIUM",
    startingPrice: 20,
    currency: "USD",
    freeTrial: false,
    rating: 4.6,
    reviewCount: 3421,
    viewCount: 2341892,
    clickCount: 723481,
    bookmarkCount: 31203,
    featured: false,
    sponsored: false,
    verified: true,
    launchedAt: "2022-12-07",
    categorySlug: "research",
    tags: ["Search", "Citations", "Real-time"],
    features: ["Pro Search", "Copilot Mode", "File Uploads", "Focus Modes", "Collections", "Image Generation", "API Access"],
    pricingPlans: [
      { name: "Free", price: 0, period: "MONTHLY", features: ["Unlimited quick searches", "5 Pro searches/day", "Basic models"] },
      { name: "Pro", price: 20, period: "MONTHLY", features: ["300+ Pro searches/day", "File uploads", "GPT-4, Claude 3, Opus", "Image generation"], isPopular: true },
      { name: "Enterprise", price: 40, period: "MONTHLY", features: ["Unlimited Pro searches", "Internal data search", "Team management", "SSO"] },
    ],
  },
  {
    id: "t9",
    slug: "notion-ai",
    name: "Notion AI",
    tagline: "AI assistant built into Notion",
    description: "Write, summarize, translate, and brainstorm directly within your Notion workspace.",
    longDescription: "Notion AI is an integrated AI assistant that helps you write, summarize, translate, and brainstorm directly within your Notion workspace. It can improve existing content, generate new ideas, and automate repetitive writing tasks. Available as an add-on to any Notion plan.",
    websiteUrl: "https://notion.so/product/ai",
    logoUrl: "https://api.dicebear.com/7.x/shapes/svg?seed=notion&backgroundColor=000000",
    pricingType: "PAID",
    startingPrice: 10,
    currency: "USD",
    freeTrial: true,
    freeTrialDays: 14,
    rating: 4.5,
    reviewCount: 5621,
    viewCount: 3123941,
    clickCount: 892341,
    bookmarkCount: 41234,
    featured: false,
    sponsored: false,
    verified: true,
    launchedAt: "2023-02-22",
    categorySlug: "productivity",
    tags: ["Notion", "Writing", "Productivity"],
    features: ["AI Writing", "Summarization", "Translation", "Q&A", "Auto-fill Tables", "Brainstorming", "Meeting Notes"],
    pricingPlans: [
      { name: "Add-on", price: 10, period: "MONTHLY", features: ["Unlimited AI responses", "Works with any Notion plan", "Priority processing"] },
    ],
  },
  {
    id: "t10",
    slug: "stable-diffusion",
    name: "Stable Diffusion",
    tagline: "Open-source AI image generation",
    description: "Generate high-quality images locally or via API with this open-source model.",
    longDescription: "Stable Diffusion is an open-source latent text-to-image diffusion model capable of generating photorealistic images from text prompts. It can be run locally on consumer hardware, making it popular among developers and artists. The ecosystem includes SDXL, ControlNet, LoRA training, and more.",
    websiteUrl: "https://stability.ai",
    logoUrl: "https://api.dicebear.com/7.x/shapes/svg?seed=stable&backgroundColor=9333ea",
    pricingType: "FREE",
    startingPrice: 0,
    currency: "USD",
    freeTrial: false,
    rating: 4.6,
    reviewCount: 7823,
    viewCount: 5621893,
    clickCount: 1348923,
    bookmarkCount: 67234,
    featured: true,
    sponsored: false,
    verified: true,
    launchedAt: "2022-08-22",
    categorySlug: "image",
    tags: ["Open Source", "Self-hosted", "SDXL", "ControlNet"],
    features: ["SDXL Model", "ControlNet", "LoRA Training", "Image-to-Image", "Inpainting", "Upscaling", "API Access"],
    pricingPlans: [
      { name: "Community", price: 0, period: "MONTHLY", features: ["Open source models", "Self-hosting", "Community support"] },
      { name: "Pro", price: 9, period: "MONTHLY", features: ["API access", "Premium models", "Faster generation"], isPopular: true },
      { name: "Enterprise", price: 99, period: "MONTHLY", features: ["Dedicated GPUs", "Custom models", "SLA", "Priority support"] },
    ],
  },
  {
    id: "t11",
    slug: "synthesia",
    name: "Synthesia",
    tagline: "Create AI videos with avatars",
    description: "Generate professional videos with AI avatars in 120+ languages without a camera.",
    longDescription: "Synthesia is an AI video generation platform that lets you create professional videos using AI avatars. Type your script, choose an avatar, and generate a video in minutes. Perfect for training, marketing, and internal communications. Supports 120+ languages and 140+ AI avatars.",
    websiteUrl: "https://synthesia.io",
    logoUrl: "https://api.dicebear.com/7.x/shapes/svg?seed=synthesia&backgroundColor=dc2626",
    pricingType: "PAID",
    startingPrice: 29,
    currency: "USD",
    freeTrial: true,
    freeTrialDays: 14,
    rating: 4.4,
    reviewCount: 2341,
    viewCount: 1234892,
    clickCount: 423481,
    bookmarkCount: 21342,
    featured: false,
    sponsored: true,
    verified: true,
    launchedAt: "2017-12-15",
    categorySlug: "video",
    tags: ["Video Avatars", "Multilingual", "Corporate"],
    features: ["140+ AI Avatars", "120+ Languages", "Custom Avatars", "Templates", "Voice Cloning", "Screen Recording", "Collaboration"],
    pricingPlans: [
      { name: "Starter", price: 29, period: "MONTHLY", features: ["10 min/month", "70+ AI avatars", "120+ languages"] },
      { name: "Creator", price: 89, period: "MONTHLY", features: ["30 min/month", "140+ avatars", "Custom avatars", "No watermark"], isPopular: true },
      { name: "Enterprise", price: 0, period: "MONTHLY", features: ["Custom minutes", "SSO", "Premium avatars", "Dedicated support"] },
    ],
  },
  {
    id: "t12",
    slug: "grammarly",
    name: "Grammarly",
    tagline: "AI-powered writing assistant",
    description: "Improve your writing with AI-powered grammar, tone, and style suggestions.",
    longDescription: "Grammarly is an AI-powered writing assistant that helps you write with confidence. It checks grammar, spelling, and punctuation in real-time, suggests vocabulary improvements, and provides tone adjustments. GrammarlyGO brings generative AI to compose, rewrite, and ideate.",
    websiteUrl: "https://grammarly.com",
    logoUrl: "https://api.dicebear.com/7.x/shapes/svg?seed=grammarly&backgroundColor=15c39a",
    pricingType: "FREEMIUM",
    startingPrice: 12,
    currency: "USD",
    freeTrial: true,
    rating: 4.5,
    reviewCount: 12341,
    viewCount: 8921341,
    clickCount: 2341892,
    bookmarkCount: 78234,
    featured: false,
    sponsored: false,
    verified: true,
    launchedAt: "2009-07-01",
    categorySlug: "writing",
    tags: ["Grammar", "Style", "Tone Detection"],
    features: ["Grammar Check", "Tone Detection", "Plagiarism Checker", "GrammarlyGO AI", "Browser Extension", "Citations", "Goals"],
    pricingPlans: [
      { name: "Free", price: 0, period: "MONTHLY", features: ["Basic grammar", "Spelling", "Punctuation"] },
      { name: "Premium", price: 12, period: "MONTHLY", features: ["Advanced suggestions", "Tone adjustments", "Plagiarism checker", "Vocabulary"], isPopular: true },
      { name: "Business", price: 15, period: "MONTHLY", features: ["Style guide", "Brand tones", "Analytics", "Admin console"] },
    ],
  },
];

export type PricingTier = {
  name: string;
  monthly: number;
  yearly: number;
  description: string;
  features: string[];
  isPopular: boolean;
  cta: string;
  stripe: string;
  highlight?: boolean;
};

export const PLATFORM_PRICING_TIERS: PricingTier[] = [
  {
    name: "Free",
    monthly: 0,
    yearly: 0,
    description: "Perfect for individuals exploring AI tools",
    features: ["Browse 100K+ AI tools", "Basic search & filters", "Save up to 25 bookmarks", "1 public collection", "Community access", "Weekly newsletter"],
    isPopular: false,
    cta: "Get Started Free",
    stripe: "https://buy.stripe.com/fZu14m4Pe3QH8KkgwC6Zy0m",
  },
  {
    name: "Pro",
    monthly: 19,
    yearly: 15,
    description: "For power users and content creators",
    features: ["Everything in Free", "Unlimited bookmarks & collections", "Advanced AI search", "Tool comparison (up to 5)", "Personal AI recommendations", "Early access to new tools", "Priority support", "No ads"],
    isPopular: true,
    cta: "Start Pro Trial",
    stripe: "https://buy.stripe.com/5kQ00i81qbj97Gg1BI6Zy0n",
    highlight: true,
  },
  {
    name: "Business",
    monthly: 79,
    yearly: 65,
    description: "For teams and growing businesses",
    features: ["Everything in Pro", "Up to 10 team members", "Shared collections", "Team analytics dashboard", "API access (10K calls/mo)", "Custom collections", "SSO authentication", "Dedicated support"],
    isPopular: false,
    cta: "Start Business Trial",
    stripe: "https://buy.stripe.com/6oUfZgftS5YP7Ggbci6Zy0o",
  },
  {
    name: "Enterprise",
    monthly: 299,
    yearly: 249,
    description: "For large organizations with custom needs",
    features: ["Everything in Business", "Unlimited team members", "White-label branding", "Custom integrations", "Dedicated account manager", "99.9% SLA", "On-premise deployment", "Custom AI models"],
    isPopular: false,
    cta: "Contact Sales",
    stripe: "https://buy.stripe.com/aFafZg1D29b15y8gwC6Zy0p",
  },
];

export type Review = {
  id: string;
  toolId: string;
  userName: string;
  userAvatar: string;
  rating: number;
  title: string;
  content: string;
  helpfulCount: number;
  verified: boolean;
  createdAt: string;
};

export const REVIEWS: Review[] = [
  { id: "r1", toolId: "t1", userName: "Sarah Chen", userAvatar: "SC", rating: 5, title: "Indispensable for daily work", content: "ChatGPT has completely transformed how I approach problem-solving. From drafting emails to brainstorming content ideas, it's become my go-to assistant. The GPT-4 model is remarkably capable.", helpfulCount: 234, verified: true, createdAt: "2024-01-15" },
  { id: "r2", toolId: "t1", userName: "Marcus Rodriguez", userAvatar: "MR", rating: 4, title: "Powerful but pricey", content: "Incredible tool for coding and analysis. The code interpreter alone is worth the subscription. Only downside is the usage cap on the Plus plan during peak hours.", helpfulCount: 156, verified: true, createdAt: "2024-02-03" },
  { id: "r3", toolId: "t2", userName: "Emily Watson", userAvatar: "EW", rating: 5, title: "Best AI art generator", content: "Nothing comes close to Midjourney's artistic quality. The V6 model produces stunning images with incredible detail. The style reference feature is a game-changer for maintaining consistency.", helpfulCount: 189, verified: true, createdAt: "2024-01-22" },
  { id: "r4", toolId: "t3", userName: "David Kim", userAvatar: "DK", rating: 5, title: "Best AI for long documents", content: "Claude's 200K context window is unmatched. I can upload entire books and have intelligent conversations about them. The writing quality is more nuanced than competitors.", helpfulCount: 142, verified: true, createdAt: "2024-02-14" },
  { id: "r5", toolId: "t4", userName: "Lisa Park", userAvatar: "LP", rating: 4, title: "Saves hours every day", content: "Copilot has become an essential part of my workflow. The completions are spot-on most of the time, and the chat feature helps me understand unfamiliar codebases quickly.", helpfulCount: 98, verified: true, createdAt: "2024-01-08" },
  { id: "r6", toolId: "t7", userName: "Alex Turner", userAvatar: "AT", rating: 5, title: "Revolutionary voice cloning", content: "The voice cloning quality is scary good. I cloned my own voice in 30 seconds and it sounds indistinguishable from the original. Great for content creators.", helpfulCount: 167, verified: true, createdAt: "2024-02-20" },
];

export type Testimonial = {
  id: string;
  name: string;
  role: string;
  company: string;
  avatar: string;
  content: string;
  rating: number;
};

export const TESTIMONIALS: Testimonial[] = [
  { id: "tm1", name: "Jennifer Hayes", role: "Product Manager", company: "TechFlow", avatar: "JH", content: "AIToolsHub has become our team's go-to resource for discovering new AI tools. The comparison feature alone saves us hours of research every week.", rating: 5 },
  { id: "tm2", name: "Raj Patel", role: "CTO", company: "StartupX", avatar: "RP", content: "The directory is incredibly comprehensive. We've found 3 tools through AIToolsHub that have transformed our development workflow.", rating: 5 },
  { id: "tm3", name: "Maria Garcia", role: "Marketing Director", company: "GrowthLabs", avatar: "MG", content: "As a marketer, I love how easy it is to find and compare AI tools for different use cases. The sponsored listings are actually relevant, not spammy.", rating: 5 },
  { id: "tm4", name: "Tom Anderson", role: "Indie Developer", company: "SoloBuilds", avatar: "TA", content: "The API access lets me integrate tool data directly into my own app. Documentation is excellent and the rate limits are generous.", rating: 5 },
];

export type BlogPost = {
  id: string;
  slug: string;
  title: string;
  excerpt: string;
  content: string;
  author: string;
  authorAvatar: string;
  publishedAt: string;
  readTime: string;
  category: string;
  coverGradient: string;
};

export const BLOG_POSTS: BlogPost[] = [
  { id: "b1", slug: "best-ai-tools-2024", title: "The 25 Best AI Tools of 2024: A Complete Guide", excerpt: "From content creation to coding, we've tested and ranked the most powerful AI tools that are transforming workflows this year.", content: "Full article content...", author: "Sarah Mitchell", authorAvatar: "SM", publishedAt: "2024-03-15", readTime: "12 min", category: "Guides", coverGradient: "from-violet-500 to-purple-500" },
  { id: "b2", slug: "ai-image-generation-comparison", title: "Midjourney vs DALL-E vs Stable Diffusion: Which Wins in 2024?", excerpt: "We put the top three AI image generators head-to-head across 10 categories. The results might surprise you.", content: "Full article content...", author: "James Lee", authorAvatar: "JL", publishedAt: "2024-03-12", readTime: "8 min", category: "Comparisons", coverGradient: "from-pink-500 to-rose-500" },
  { id: "b3", slug: "ai-coding-assistants", title: "How AI Coding Assistants Are Revolutionizing Software Development", excerpt: "GitHub Copilot, Cursor, and Codeium are changing how developers write code. Here's what you need to know.", content: "Full article content...", author: "Priya Sharma", authorAvatar: "PS", publishedAt: "2024-03-10", readTime: "10 min", category: "Development", coverGradient: "from-emerald-500 to-teal-500" },
];

// ---------------------------------------------------------------------
// i18n STRINGS â€” 5 languages with full RTL support for Arabic
// ---------------------------------------------------------------------

export type Locale = "en" | "ar" | "es" | "zh" | "hi";

export const LOCALES: { code: Locale; name: string; nativeName: string; flag: string; rtl?: boolean }[] = [
  { code: "en", name: "English", nativeName: "English", flag: "ðŸ‡¬ðŸ‡§" },
  { code: "ar", name: "Arabic", nativeName: "Ø§Ù„Ø¹Ø±Ø¨ÙŠØ©", flag: "ðŸ‡¸ðŸ‡¦", rtl: true },
  { code: "es", name: "Spanish", nativeName: "EspaÃ±ol", flag: "ðŸ‡ªðŸ‡¸" },
  { code: "zh", name: "Chinese", nativeName: "ä¸­æ–‡", flag: "ðŸ‡¨ðŸ‡³" },
  { code: "hi", name: "Hindi", nativeName: "à¤¹à¤¿à¤¨à¥à¤¦à¥€", flag: "ðŸ‡®ðŸ‡³" },
];

export const I18N: Record<Locale, Record<string, string>> = {
  en: {
    "nav.discover": "Discover",
    "nav.categories": "Categories",
    "nav.compare": "Compare",
    "nav.pricing": "Pricing",
    "nav.blog": "Blog",
    "nav.api": "API Docs",
    "nav.signIn": "Sign In",
    "nav.signUp": "Get Started",
    "nav.dashboard": "Dashboard",
    "hero.badge": "Trusted by 2M+ creators worldwide",
    "hero.title": "Discover the Best AI Tools, Curated & Ranked",
    "hero.subtitle": "Explore 100,000+ AI tools across 50+ categories. Compare features, read verified reviews, and find the perfect AI solution for your workflow.",
    "hero.searchPlaceholder": "Search for AI tools, categories, or use cases...",
    "hero.searchButton": "Search",
    "hero.aiSearchHint": "Try: \"AI for writing marketing copy\"",
    "stats.tools": "AI Tools",
    "stats.categories": "Categories",
    "stats.users": "Monthly Users",
    "stats.reviews": "Reviews",
    "categories.title": "Browse by Category",
    "categories.subtitle": "Find the perfect AI tools for any use case",
    "categories.viewAll": "View all categories",
    "featured.title": "Featured AI Tools",
    "featured.subtitle": "Hand-picked tools our community loves this week",
    "featured.viewAll": "View all tools",
    "directory.title": "Explore the Directory",
    "directory.subtitle": "Filter, search, and discover AI tools that match your needs",
    "directory.results": "tools found",
    "directory.filters": "Filters",
    "directory.sortBy": "Sort by",
    "directory.category": "Category",
    "directory.pricing": "Pricing",
    "directory.rating": "Rating",
    "directory.sort.popular": "Most Popular",
    "directory.sort.rated": "Highest Rated",
    "directory.sort.newest": "Newest",
    "directory.sort.priceLow": "Price: Low to High",
    "directory.sort.priceHigh": "Price: High to Low",
    "directory.empty": "No tools match your filters. Try adjusting your search.",
    "directory.clearFilters": "Clear all filters",
    "directory.loadMore": "Load more tools",
    "pricing.free": "Free",
    "pricing.freemium": "Freemium",
    "pricing.paid": "Paid",
    "pricing.freeTrial": "Free Trial",
    "pricing.contactPricing": "Contact for Pricing",
    "pricing.perMonth": "/mo",
    "pricing.perYear": "/yr",
    "pricing.title": "Simple, Transparent Pricing",
    "pricing.subtitle": "Choose the plan that fits your needs. Cancel anytime.",
    "pricing.monthly": "Monthly",
    "pricing.yearly": "Yearly",
    "pricing.save": "Save 20%",
    "pricing.popular": "Most Popular",
    "pricing.cta.free": "Get Started Free",
    "pricing.cta.pro": "Start Pro Trial",
    "pricing.cta.business": "Start Business Trial",
    "pricing.cta.enterprise": "Contact Sales",
    "pricing.cta.currentPlan": "Current Plan",
    "compare.title": "Compare AI Tools Side by Side",
    "compare.subtitle": "Add tools to compare features, pricing, and ratings",
    "compare.addButton": "Add tool to compare",
    "compare.remove": "Remove",
    "compare.clearAll": "Clear all",
    "compare.empty": "Add at least 2 tools to start comparing",
    "compare.feature": "Feature",
    "compare.pricing": "Pricing",
    "compare.rating": "Rating",
    "compare.reviews": "Reviews",
    "compare.category": "Category",
    "compare.tags": "Tags",
    "compare.website": "Website",
    "compare.addedAt": "Added",
    "userDashboard.title": "Your Dashboard",
    "userDashboard.subtitle": "Manage your bookmarks, collections, and reviews",
    "userDashboard.overview": "Overview",
    "userDashboard.bookmarks": "Bookmarks",
    "userDashboard.collections": "Collections",
    "userDashboard.reviews": "Reviews",
    "userDashboard.analytics": "Analytics",
    "userDashboard.totalBookmarks": "Total Bookmarks",
    "userDashboard.totalCollections": "Collections",
    "userDashboard.totalReviews": "Reviews Written",
    "userDashboard.recentActivity": "Recent Activity",
    "adminDashboard.title": "Admin Dashboard",
    "adminDashboard.subtitle": "Manage tools, users, and platform analytics",
    "adminDashboard.tools": "Tools",
    "adminDashboard.analytics": "Analytics",
    "adminDashboard.moderation": "Moderation",
    "adminDashboard.users": "Users",
    "adminDashboard.auditLogs": "Audit Logs",
    "adminDashboard.totalTools": "Total Tools",
    "adminDashboard.totalUsers": "Total Users",
    "adminDashboard.mrr": "Monthly Revenue",
    "adminDashboard.pendingReviews": "Pending Reviews",
    "cta.title": "Ready to Transform Your Workflow?",
    "cta.subtitle": "Join 2M+ creators, developers, and businesses using AIToolsHub to find their perfect AI stack.",
    "cta.button": "Start Free Today",
    "footer.about": "About",
    "footer.product": "Product",
    "footer.resources": "Resources",
    "footer.legal": "Legal",
    "footer.company": "Company",
    "footer.rights": "All rights reserved.",
    "footer.madeWith": "Made with",
    "footer.forCreators": "for creators",
    "common.viewDetails": "View Details",
    "common.visit": "Visit Website",
    "common.bookmark": "Bookmark",
    "common.bookmarked": "Bookmarked",
    "common.share": "Share",
    "common.compare": "Compare",
    "common.added": "Added",
    "common.free": "FREE",
    "common.features": "Features",
    "common.pricing": "Pricing",
    "common.reviews": "Reviews",
    "common.alternatives": "Alternatives",
    "common.screenshots": "Screenshots",
    "common.verified": "Verified",
    "common.sponsored": "Sponsored",
    "common.featured": "Featured",
    "common.search": "Search",
    "common.close": "Close",
    "common.apply": "Apply",
    "common.cancel": "Cancel",
    "common.all": "All",
  },
  ar: {
    "nav.discover": "Ø§ÙƒØªØ´Ù",
    "nav.categories": "Ø§Ù„ÙØ¦Ø§Øª",
    "nav.compare": "Ù‚Ø§Ø±Ù†",
    "nav.pricing": "Ø§Ù„Ø£Ø³Ø¹Ø§Ø±",
    "nav.blog": "Ø§Ù„Ù…Ø¯ÙˆÙ†Ø©",
    "nav.api": "ÙˆØ«Ø§Ø¦Ù‚ API",
    "nav.signIn": "ØªØ³Ø¬ÙŠÙ„ Ø§Ù„Ø¯Ø®ÙˆÙ„",
    "nav.signUp": "Ø§Ø¨Ø¯Ø£ Ø§Ù„Ø¢Ù†",
    "nav.dashboard": "Ù„ÙˆØ­Ø© Ø§Ù„ØªØ­ÙƒÙ…",
    "hero.badge": "Ù…ÙˆØ«ÙˆÙ‚ Ø¨Ù‡ Ù…Ù† Ù‚Ø¨Ù„ Ø£ÙƒØ«Ø± Ù…Ù† 2 Ù…Ù„ÙŠÙˆÙ† Ù…Ø¨Ø¯Ø¹ Ø­ÙˆÙ„ Ø§Ù„Ø¹Ø§Ù„Ù…",
    "hero.title": "Ø§ÙƒØªØ´Ù Ø£ÙØ¶Ù„ Ø£Ø¯ÙˆØ§Øª Ø§Ù„Ø°ÙƒØ§Ø¡ Ø§Ù„Ø§ØµØ·Ù†Ø§Ø¹ÙŠØŒ Ù…Ù†Ø³Ù‚Ø© ÙˆÙ…Ø±ØªØ¨Ø©",
    "hero.subtitle": "Ø§Ø³ØªÙƒØ´Ù Ø£ÙƒØ«Ø± Ù…Ù† 100,000 Ø£Ø¯Ø§Ø© Ø°ÙƒØ§Ø¡ Ø§ØµØ·Ù†Ø§Ø¹ÙŠ ÙÙŠ Ø£ÙƒØ«Ø± Ù…Ù† 50 ÙØ¦Ø©. Ù‚Ø§Ø±Ù† Ø§Ù„Ù…ÙŠØ²Ø§ØªØŒ ÙˆØ§Ù‚Ø±Ø£ Ø§Ù„Ù…Ø±Ø§Ø¬Ø¹Ø§Øª Ø§Ù„Ù…ÙˆØ«Ù‚Ø©ØŒ ÙˆØ§Ø¹Ø«Ø± Ø¹Ù„Ù‰ Ø­Ù„ Ø§Ù„Ø°ÙƒØ§Ø¡ Ø§Ù„Ø§ØµØ·Ù†Ø§Ø¹ÙŠ Ø§Ù„Ù…Ø«Ø§Ù„ÙŠ Ù„Ø³ÙŠØ± Ø¹Ù…Ù„Ùƒ.",
    "hero.searchPlaceholder": "Ø§Ø¨Ø­Ø« Ø¹Ù† Ø£Ø¯ÙˆØ§Øª Ø§Ù„Ø°ÙƒØ§Ø¡ Ø§Ù„Ø§ØµØ·Ù†Ø§Ø¹ÙŠ Ø£Ùˆ Ø§Ù„ÙØ¦Ø§Øª Ø£Ùˆ Ø­Ø§Ù„Ø§Øª Ø§Ù„Ø§Ø³ØªØ®Ø¯Ø§Ù…...",
    "hero.searchButton": "Ø¨Ø­Ø«",
    "hero.aiSearchHint": "Ø¬Ø±Ø¨: \"Ø§Ù„Ø°ÙƒØ§Ø¡ Ø§Ù„Ø§ØµØ·Ù†Ø§Ø¹ÙŠ Ù„ÙƒØªØ§Ø¨Ø© Ø§Ù„Ù…Ø­ØªÙˆÙ‰ Ø§Ù„ØªØ³ÙˆÙŠÙ‚ÙŠ\"",
    "stats.tools": "Ø£Ø¯Ø§Ø© Ø°ÙƒØ§Ø¡ Ø§ØµØ·Ù†Ø§Ø¹ÙŠ",
    "stats.categories": "ÙØ¦Ø©",
    "stats.users": "Ù…Ø³ØªØ®Ø¯Ù… Ø´Ù‡Ø±ÙŠØ§Ù‹",
    "stats.reviews": "Ù…Ø±Ø§Ø¬Ø¹Ø©",
    "categories.title": "ØªØµÙØ­ Ø­Ø³Ø¨ Ø§Ù„ÙØ¦Ø©",
    "categories.subtitle": "Ø§Ø¹Ø«Ø± Ø¹Ù„Ù‰ Ø£Ø¯ÙˆØ§Øª Ø§Ù„Ø°ÙƒØ§Ø¡ Ø§Ù„Ø§ØµØ·Ù†Ø§Ø¹ÙŠ Ø§Ù„Ù…Ø«Ø§Ù„ÙŠØ© Ù„Ø£ÙŠ Ø­Ø§Ù„Ø© Ø§Ø³ØªØ®Ø¯Ø§Ù…",
    "categories.viewAll": "Ø¹Ø±Ø¶ Ø¬Ù…ÙŠØ¹ Ø§Ù„ÙØ¦Ø§Øª",
    "featured.title": "Ø£Ø¯ÙˆØ§Øª Ø§Ù„Ø°ÙƒØ§Ø¡ Ø§Ù„Ø§ØµØ·Ù†Ø§Ø¹ÙŠ Ø§Ù„Ù…Ù…ÙŠØ²Ø©",
    "featured.subtitle": "Ø£Ø¯ÙˆØ§Øª Ù…Ø®ØªØ§Ø±Ø© ÙŠØ¯ÙˆÙŠØ§Ù‹ ÙŠØ­Ø¨Ù‡Ø§ Ù…Ø¬ØªÙ…Ø¹Ù†Ø§ Ù‡Ø°Ø§ Ø§Ù„Ø£Ø³Ø¨ÙˆØ¹",
    "featured.viewAll": "Ø¹Ø±Ø¶ Ø¬Ù…ÙŠØ¹ Ø§Ù„Ø£Ø¯ÙˆØ§Øª",
    "directory.title": "Ø§Ø³ØªÙƒØ´Ù Ø§Ù„Ø¯Ù„ÙŠÙ„",
    "directory.subtitle": "Ù‚Ù… Ø¨Ø§Ù„ØªØµÙÙŠØ© ÙˆØ§Ù„Ø¨Ø­Ø« ÙˆØ§ÙƒØªØ´Ù Ø£Ø¯ÙˆØ§Øª Ø§Ù„Ø°ÙƒØ§Ø¡ Ø§Ù„Ø§ØµØ·Ù†Ø§Ø¹ÙŠ Ø§Ù„ØªÙŠ ØªÙ†Ø§Ø³Ø¨ Ø§Ø­ØªÙŠØ§Ø¬Ø§ØªÙƒ",
    "directory.results": "Ø£Ø¯Ø§Ø© Ù…ÙˆØ¬ÙˆØ¯Ø©",
    "directory.filters": "Ø§Ù„Ù…Ø±Ø´Ø­Ø§Øª",
    "directory.sortBy": "ØªØ±ØªÙŠØ¨ Ø­Ø³Ø¨",
    "directory.category": "Ø§Ù„ÙØ¦Ø©",
    "directory.pricing": "Ø§Ù„Ø£Ø³Ø¹Ø§Ø±",
    "directory.rating": "Ø§Ù„ØªÙ‚ÙŠÙŠÙ…",
    "directory.sort.popular": "Ø§Ù„Ø£ÙƒØ«Ø± Ø´Ø¹Ø¨ÙŠØ©",
    "directory.sort.rated": "Ø§Ù„Ø£Ø¹Ù„Ù‰ ØªÙ‚ÙŠÙŠÙ…Ø§Ù‹",
    "directory.sort.newest": "Ø§Ù„Ø£Ø­Ø¯Ø«",
    "directory.sort.priceLow": "Ø§Ù„Ø³Ø¹Ø±: Ù…Ù† Ø§Ù„Ø£Ù‚Ù„ Ø¥Ù„Ù‰ Ø§Ù„Ø£Ø¹Ù„Ù‰",
    "directory.sort.priceHigh": "Ø§Ù„Ø³Ø¹Ø±: Ù…Ù† Ø§Ù„Ø£Ø¹Ù„Ù‰ Ø¥Ù„Ù‰ Ø§Ù„Ø£Ù‚Ù„",
    "directory.empty": "Ù„Ø§ ØªÙˆØ¬Ø¯ Ø£Ø¯ÙˆØ§Øª ØªØ·Ø§Ø¨Ù‚ Ù…Ø±Ø´Ø­Ø§ØªÙƒ. Ø­Ø§ÙˆÙ„ ØªØ¹Ø¯ÙŠÙ„ Ø§Ù„Ø¨Ø­Ø«.",
    "directory.clearFilters": "Ù…Ø³Ø­ Ø¬Ù…ÙŠØ¹ Ø§Ù„Ù…Ø±Ø´Ø­Ø§Øª",
    "directory.loadMore": "ØªØ­Ù…ÙŠÙ„ Ø§Ù„Ù…Ø²ÙŠØ¯ Ù…Ù† Ø§Ù„Ø£Ø¯ÙˆØ§Øª",
    "pricing.free": "Ù…Ø¬Ø§Ù†ÙŠ",
    "pricing.freemium": "Ù…Ø¬Ø§Ù†ÙŠ Ø¬Ø²Ø¦ÙŠØ§Ù‹",
    "pricing.paid": "Ù…Ø¯ÙÙˆØ¹",
    "pricing.freeTrial": "ØªØ¬Ø±Ø¨Ø© Ù…Ø¬Ø§Ù†ÙŠØ©",
    "pricing.contactPricing": "Ø§ØªØµÙ„ Ù„Ù„ØªØ³Ø¹ÙŠØ±",
    "pricing.perMonth": "/Ø´Ù‡Ø±",
    "pricing.perYear": "/Ø³Ù†Ø©",
    "pricing.title": "Ø£Ø³Ø¹Ø§Ø± Ø¨Ø³ÙŠØ·Ø© ÙˆØ´ÙØ§ÙØ©",
    "pricing.subtitle": "Ø§Ø®ØªØ± Ø§Ù„Ø®Ø·Ø© Ø§Ù„ØªÙŠ ØªÙ†Ø§Ø³Ø¨ Ø§Ø­ØªÙŠØ§Ø¬Ø§ØªÙƒ. ÙŠÙ…ÙƒÙ†Ùƒ Ø§Ù„Ø¥Ù„ØºØ§Ø¡ ÙÙŠ Ø£ÙŠ ÙˆÙ‚Øª.",
    "pricing.monthly": "Ø´Ù‡Ø±ÙŠ",
    "pricing.yearly": "Ø³Ù†ÙˆÙŠ",
    "pricing.save": "ÙˆÙØ± 20%",
    "pricing.popular": "Ø§Ù„Ø£ÙƒØ«Ø± Ø´Ø¹Ø¨ÙŠØ©",
    "pricing.cta.free": "Ø§Ø¨Ø¯Ø£ Ù…Ø¬Ø§Ù†Ø§Ù‹",
    "pricing.cta.pro": "Ø§Ø¨Ø¯Ø£ ØªØ¬Ø±Ø¨Ø© Pro",
    "pricing.cta.business": "Ø§Ø¨Ø¯Ø£ ØªØ¬Ø±Ø¨Ø© Ø§Ù„Ø£Ø¹Ù…Ø§Ù„",
    "pricing.cta.enterprise": "Ø§ØªØµÙ„ Ø¨Ø§Ù„Ù…Ø¨ÙŠØ¹Ø§Øª",
    "pricing.cta.currentPlan": "Ø§Ù„Ø®Ø·Ø© Ø§Ù„Ø­Ø§Ù„ÙŠØ©",
    "compare.title": "Ù‚Ø§Ø±Ù† Ø£Ø¯ÙˆØ§Øª Ø§Ù„Ø°ÙƒØ§Ø¡ Ø§Ù„Ø§ØµØ·Ù†Ø§Ø¹ÙŠ Ø¬Ù†Ø¨Ø§Ù‹ Ø¥Ù„Ù‰ Ø¬Ù†Ø¨",
    "compare.subtitle": "Ø£Ø¶Ù Ø£Ø¯ÙˆØ§Øª Ù„Ù„Ù…Ù‚Ø§Ø±Ù†Ø© Ø¨ÙŠÙ† Ø§Ù„Ù…ÙŠØ²Ø§Øª ÙˆØ§Ù„Ø£Ø³Ø¹Ø§Ø± ÙˆØ§Ù„ØªÙ‚ÙŠÙŠÙ…Ø§Øª",
    "compare.addButton": "Ø£Ø¶Ù Ø£Ø¯Ø§Ø© Ù„Ù„Ù…Ù‚Ø§Ø±Ù†Ø©",
    "compare.remove": "Ø¥Ø²Ø§Ù„Ø©",
    "compare.clearAll": "Ù…Ø³Ø­ Ø§Ù„ÙƒÙ„",
    "compare.empty": "Ø£Ø¶Ù Ø£Ø¯Ø§ØªÙŠÙ† Ø¹Ù„Ù‰ Ø§Ù„Ø£Ù‚Ù„ Ù„Ø¨Ø¯Ø¡ Ø§Ù„Ù…Ù‚Ø§Ø±Ù†Ø©",
    "compare.feature": "Ø§Ù„Ù…ÙŠØ²Ø©",
    "compare.pricing": "Ø§Ù„Ø£Ø³Ø¹Ø§Ø±",
    "compare.rating": "Ø§Ù„ØªÙ‚ÙŠÙŠÙ…",
    "compare.reviews": "Ø§Ù„Ù…Ø±Ø§Ø¬Ø¹Ø§Øª",
    "compare.category": "Ø§Ù„ÙØ¦Ø©",
    "compare.tags": "Ø§Ù„Ø¹Ù„Ø§Ù…Ø§Øª",
    "compare.website": "Ø§Ù„Ù…ÙˆÙ‚Ø¹",
    "compare.addedAt": "Ø£Ø¶ÙŠÙØª ÙÙŠ",
    "userDashboard.title": "Ù„ÙˆØ­Ø© Ø§Ù„ØªØ­ÙƒÙ… Ø§Ù„Ø®Ø§ØµØ© Ø¨Ùƒ",
    "userDashboard.subtitle": "Ø¥Ø¯Ø§Ø±Ø© Ø§Ù„Ø¥Ø´Ø§Ø±Ø§Øª Ø§Ù„Ù…Ø±Ø¬Ø¹ÙŠØ© ÙˆØ§Ù„Ù…Ø¬Ù…ÙˆØ¹Ø§Øª ÙˆØ§Ù„Ù…Ø±Ø§Ø¬Ø¹Ø§Øª",
    "userDashboard.overview": "Ù†Ø¸Ø±Ø© Ø¹Ø§Ù…Ø©",
    "userDashboard.bookmarks": "Ø§Ù„Ø¥Ø´Ø§Ø±Ø§Øª Ø§Ù„Ù…Ø±Ø¬Ø¹ÙŠØ©",
    "userDashboard.collections": "Ø§Ù„Ù…Ø¬Ù…ÙˆØ¹Ø§Øª",
    "userDashboard.reviews": "Ø§Ù„Ù…Ø±Ø§Ø¬Ø¹Ø§Øª",
    "userDashboard.analytics": "Ø§Ù„ØªØ­Ù„ÙŠÙ„Ø§Øª",
    "userDashboard.totalBookmarks": "Ø¥Ø¬Ù…Ø§Ù„ÙŠ Ø§Ù„Ø¥Ø´Ø§Ø±Ø§Øª Ø§Ù„Ù…Ø±Ø¬Ø¹ÙŠØ©",
    "userDashboard.totalCollections": "Ø§Ù„Ù…Ø¬Ù…ÙˆØ¹Ø§Øª",
    "userDashboard.totalReviews": "Ø§Ù„Ù…Ø±Ø§Ø¬Ø¹Ø§Øª Ø§Ù„Ù…ÙƒØªÙˆØ¨Ø©",
    "userDashboard.recentActivity": "Ø§Ù„Ù†Ø´Ø§Ø· Ø§Ù„Ø£Ø®ÙŠØ±",
    "adminDashboard.title": "Ù„ÙˆØ­Ø© ØªØ­ÙƒÙ… Ø§Ù„Ù…Ø¯ÙŠØ±",
    "adminDashboard.subtitle": "Ø¥Ø¯Ø§Ø±Ø© Ø§Ù„Ø£Ø¯ÙˆØ§Øª ÙˆØ§Ù„Ù…Ø³ØªØ®Ø¯Ù…ÙŠÙ† ÙˆØªØ­Ù„ÙŠÙ„Ø§Øª Ø§Ù„Ù…Ù†ØµØ©",
    "adminDashboard.tools": "Ø§Ù„Ø£Ø¯ÙˆØ§Øª",
    "adminDashboard.analytics": "Ø§Ù„ØªØ­Ù„ÙŠÙ„Ø§Øª",
    "adminDashboard.moderation": "Ø§Ù„Ø¥Ø´Ø±Ø§Ù",
    "adminDashboard.users": "Ø§Ù„Ù…Ø³ØªØ®Ø¯Ù…ÙˆÙ†",
    "adminDashboard.auditLogs": "Ø³Ø¬Ù„Ø§Øª Ø§Ù„ØªØ¯Ù‚ÙŠÙ‚",
    "adminDashboard.totalTools": "Ø¥Ø¬Ù…Ø§Ù„ÙŠ Ø§Ù„Ø£Ø¯ÙˆØ§Øª",
    "adminDashboard.totalUsers": "Ø¥Ø¬Ù…Ø§Ù„ÙŠ Ø§Ù„Ù…Ø³ØªØ®Ø¯Ù…ÙŠÙ†",
    "adminDashboard.mrr": "Ø§Ù„Ø¥ÙŠØ±Ø§Ø¯Ø§Øª Ø§Ù„Ø´Ù‡Ø±ÙŠØ©",
    "adminDashboard.pendingReviews": "Ø§Ù„Ù…Ø±Ø§Ø¬Ø¹Ø§Øª Ø§Ù„Ù…Ø¹Ù„Ù‚Ø©",
    "cta.title": "Ù‡Ù„ Ø£Ù†Øª Ù…Ø³ØªØ¹Ø¯ Ù„ØªØ­ÙˆÙŠÙ„ Ø³ÙŠØ± Ø¹Ù…Ù„ÙƒØŸ",
    "cta.subtitle": "Ø§Ù†Ø¶Ù… Ø¥Ù„Ù‰ Ø£ÙƒØ«Ø± Ù…Ù† 2 Ù…Ù„ÙŠÙˆÙ† Ù…Ø¨Ø¯Ø¹ ÙˆÙ…Ø·ÙˆØ± ÙˆØ´Ø±ÙƒØ© ÙŠØ³ØªØ®Ø¯Ù…ÙˆÙ† AIToolsHub Ù„Ù„Ø¹Ø«ÙˆØ± Ø¹Ù„Ù‰ Ù…Ø¬Ù…ÙˆØ¹Ø© Ø§Ù„Ø°ÙƒØ§Ø¡ Ø§Ù„Ø§ØµØ·Ù†Ø§Ø¹ÙŠ Ø§Ù„Ù…Ø«Ø§Ù„ÙŠØ©.",
    "cta.button": "Ø§Ø¨Ø¯Ø£ Ù…Ø¬Ø§Ù†Ø§Ù‹ Ø§Ù„ÙŠÙˆÙ…",
    "footer.about": "Ø­ÙˆÙ„",
    "footer.product": "Ø§Ù„Ù…Ù†ØªØ¬",
    "footer.resources": "Ø§Ù„Ù…ÙˆØ§Ø±Ø¯",
    "footer.legal": "Ù‚Ø§Ù†ÙˆÙ†ÙŠ",
    "footer.company": "Ø§Ù„Ø´Ø±ÙƒØ©",
    "footer.rights": "Ø¬Ù…ÙŠØ¹ Ø§Ù„Ø­Ù‚ÙˆÙ‚ Ù…Ø­ÙÙˆØ¸Ø©.",
    "footer.madeWith": "ØµÙÙ†Ø¹ Ø¨Ù€",
    "footer.forCreators": "Ù„Ù„Ù…Ø¨Ø¯Ø¹ÙŠÙ†",
    "common.viewDetails": "Ø¹Ø±Ø¶ Ø§Ù„ØªÙØ§ØµÙŠÙ„",
    "common.visit": "Ø²ÙŠØ§Ø±Ø© Ø§Ù„Ù…ÙˆÙ‚Ø¹",
    "common.bookmark": "Ø¥Ø´Ø§Ø±Ø© Ù…Ø±Ø¬Ø¹ÙŠØ©",
    "common.bookmarked": "Ù…Ø­ÙÙˆØ¸",
    "common.share": "Ù…Ø´Ø§Ø±ÙƒØ©",
    "common.compare": "Ù‚Ø§Ø±Ù†",
    "common.added": "Ù…ÙØ¶Ø§Ù",
    "common.free": "Ù…Ø¬Ø§Ù†ÙŠ",
    "common.features": "Ø§Ù„Ù…ÙŠØ²Ø§Øª",
    "common.pricing": "Ø§Ù„Ø£Ø³Ø¹Ø§Ø±",
    "common.reviews": "Ø§Ù„Ù…Ø±Ø§Ø¬Ø¹Ø§Øª",
    "common.alternatives": "Ø§Ù„Ø¨Ø¯Ø§Ø¦Ù„",
    "common.screenshots": "Ù„Ù‚Ø·Ø§Øª Ø§Ù„Ø´Ø§Ø´Ø©",
    "common.verified": "Ù…ÙˆØ«Ù‚",
    "common.sponsored": "Ù…ÙÙ…ÙˆÙŽÙ‘Ù„",
    "common.featured": "Ù…Ù…ÙŠØ²",
    "common.search": "Ø¨Ø­Ø«",
    "common.close": "Ø¥ØºÙ„Ø§Ù‚",
    "common.apply": "ØªØ·Ø¨ÙŠÙ‚",
    "common.cancel": "Ø¥Ù„ØºØ§Ø¡",
    "common.all": "Ø§Ù„ÙƒÙ„",
  },
  es: {
    "nav.discover": "Descubrir",
    "nav.categories": "CategorÃ­as",
    "nav.compare": "Comparar",
    "nav.pricing": "Precios",
    "nav.blog": "Blog",
    "nav.api": "Docs API",
    "nav.signIn": "Iniciar SesiÃ³n",
    "nav.signUp": "Empezar",
    "nav.dashboard": "Panel",
    "hero.badge": "Con la confianza de mÃ¡s de 2M de creadores en todo el mundo",
    "hero.title": "Descubre las mejores herramientas de IA, curadas y clasificadas",
    "hero.subtitle": "Explora mÃ¡s de 100.000 herramientas de IA en mÃ¡s de 50 categorÃ­as. Compara caracterÃ­sticas, lee reseÃ±as verificadas y encuentra la soluciÃ³n de IA perfecta para tu flujo de trabajo.",
    "hero.searchPlaceholder": "Buscar herramientas de IA, categorÃ­as o casos de uso...",
    "hero.searchButton": "Buscar",
    "hero.aiSearchHint": "Prueba: \"IA para escribir copy de marketing\"",
    "stats.tools": "Herramientas de IA",
    "stats.categories": "CategorÃ­as",
    "stats.users": "Usuarios Mensuales",
    "stats.reviews": "ReseÃ±as",
    "categories.title": "Explorar por CategorÃ­a",
    "categories.subtitle": "Encuentra las herramientas de IA perfectas para cualquier caso de uso",
    "categories.viewAll": "Ver todas las categorÃ­as",
    "featured.title": "Herramientas de IA Destacadas",
    "featured.subtitle": "Herramientas seleccionadas manualmente que nuestra comunidad ama esta semana",
    "featured.viewAll": "Ver todas las herramientas",
    "directory.title": "Explorar el Directorio",
    "directory.subtitle": "Filtra, busca y descubre herramientas de IA que se adapten a tus necesidades",
    "directory.results": "herramientas encontradas",
    "directory.filters": "Filtros",
    "directory.sortBy": "Ordenar por",
    "directory.category": "CategorÃ­a",
    "directory.pricing": "Precios",
    "directory.rating": "CalificaciÃ³n",
    "directory.sort.popular": "MÃ¡s Populares",
    "directory.sort.rated": "Mejor Calificadas",
    "directory.sort.newest": "MÃ¡s Recientes",
    "directory.sort.priceLow": "Precio: Bajo a Alto",
    "directory.sort.priceHigh": "Precio: Alto a Bajo",
    "directory.empty": "Ninguna herramienta coincide con tus filtros. Intenta ajustar tu bÃºsqueda.",
    "directory.clearFilters": "Limpiar todos los filtros",
    "directory.loadMore": "Cargar mÃ¡s herramientas",
    "pricing.free": "Gratis",
    "pricing.freemium": "Freemium",
    "pricing.paid": "De Pago",
    "pricing.freeTrial": "Prueba Gratis",
    "pricing.contactPricing": "Contactar para Precios",
    "pricing.perMonth": "/mes",
    "pricing.perYear": "/aÃ±o",
    "pricing.title": "Precios Simples y Transparentes",
    "pricing.subtitle": "Elige el plan que se adapte a tus necesidades. Cancela cuando quieras.",
    "pricing.monthly": "Mensual",
    "pricing.yearly": "Anual",
    "pricing.save": "Ahorra 20%",
    "pricing.popular": "MÃ¡s Popular",
    "pricing.cta.free": "Empezar Gratis",
    "pricing.cta.pro": "Probar Pro",
    "pricing.cta.business": "Probar Business",
    "pricing.cta.enterprise": "Contactar Ventas",
    "pricing.cta.currentPlan": "Plan Actual",
    "compare.title": "Compara Herramientas de IA Lado a Lado",
    "compare.subtitle": "AÃ±ade herramientas para comparar caracterÃ­sticas, precios y calificaciones",
    "compare.addButton": "AÃ±adir herramienta para comparar",
    "compare.remove": "Quitar",
    "compare.clearAll": "Limpiar todo",
    "compare.empty": "AÃ±ade al menos 2 herramientas para empezar a comparar",
    "compare.feature": "CaracterÃ­stica",
    "compare.pricing": "Precios",
    "compare.rating": "CalificaciÃ³n",
    "compare.reviews": "ReseÃ±as",
    "compare.category": "CategorÃ­a",
    "compare.tags": "Etiquetas",
    "compare.website": "Sitio Web",
    "compare.addedAt": "AÃ±adido",
    "userDashboard.title": "Tu Panel",
    "userDashboard.subtitle": "Administra tus favoritos, colecciones y reseÃ±as",
    "userDashboard.overview": "Resumen",
    "userDashboard.bookmarks": "Favoritos",
    "userDashboard.collections": "Colecciones",
    "userDashboard.reviews": "ReseÃ±as",
    "userDashboard.analytics": "AnalÃ­ticas",
    "userDashboard.totalBookmarks": "Favoritos Totales",
    "userDashboard.totalCollections": "Colecciones",
    "userDashboard.totalReviews": "ReseÃ±as Escritas",
    "userDashboard.recentActivity": "Actividad Reciente",
    "adminDashboard.title": "Panel de AdministraciÃ³n",
    "adminDashboard.subtitle": "Administra herramientas, usuarios y analÃ­ticas de la plataforma",
    "adminDashboard.tools": "Herramientas",
    "adminDashboard.analytics": "AnalÃ­ticas",
    "adminDashboard.moderation": "ModeraciÃ³n",
    "adminDashboard.users": "Usuarios",
    "adminDashboard.auditLogs": "Registros de AuditorÃ­a",
    "adminDashboard.totalTools": "Herramientas Totales",
    "adminDashboard.totalUsers": "Usuarios Totales",
    "adminDashboard.mrr": "Ingresos Mensuales",
    "adminDashboard.pendingReviews": "ReseÃ±as Pendientes",
    "cta.title": "Â¿Listo para Transformar Tu Flujo de Trabajo?",
    "cta.subtitle": "Ãšnete a mÃ¡s de 2M de creadores, desarrolladores y empresas que usan AIToolsHub para encontrar su stack de IA perfecto.",
    "cta.button": "Empezar Gratis Hoy",
    "footer.about": "Acerca de",
    "footer.product": "Producto",
    "footer.resources": "Recursos",
    "footer.legal": "Legal",
    "footer.company": "Empresa",
    "footer.rights": "Todos los derechos reservados.",
    "footer.madeWith": "Hecho con",
    "footer.forCreators": "para creadores",
    "common.viewDetails": "Ver Detalles",
    "common.visit": "Visitar Sitio",
    "common.bookmark": "Favorito",
    "common.bookmarked": "Guardado",
    "common.share": "Compartir",
    "common.compare": "Comparar",
    "common.added": "AÃ±adido",
    "common.free": "GRATIS",
    "common.features": "CaracterÃ­sticas",
    "common.pricing": "Precios",
    "common.reviews": "ReseÃ±as",
    "common.alternatives": "Alternativas",
    "common.screenshots": "Capturas",
    "common.verified": "Verificado",
    "common.sponsored": "Patrocinado",
    "common.featured": "Destacado",
    "common.search": "Buscar",
    "common.close": "Cerrar",
    "common.apply": "Aplicar",
    "common.cancel": "Cancelar",
    "common.all": "Todos",
  },
  zh: {
    "nav.discover": "å‘çŽ°",
    "nav.categories": "åˆ†ç±»",
    "nav.compare": "å¯¹æ¯”",
    "nav.pricing": "ä»·æ ¼",
    "nav.blog": "åšå®¢",
    "nav.api": "APIæ–‡æ¡£",
    "nav.signIn": "ç™»å½•",
    "nav.signUp": "å¼€å§‹ä½¿ç”¨",
    "nav.dashboard": "æŽ§åˆ¶å°",
    "hero.badge": "å…¨çƒè¶…è¿‡200ä¸‡åˆ›ä½œè€…çš„ä¿¡èµ–ä¹‹é€‰",
    "hero.title": "å‘çŽ°æœ€å¥½çš„AIå·¥å…·ï¼Œç²¾å¿ƒç­–åˆ’å’ŒæŽ’å",
    "hero.subtitle": "æŽ¢ç´¢50å¤šä¸ªåˆ†ç±»ä¸­çš„10ä¸‡å¤šä¸ªAIå·¥å…·ã€‚æ¯”è¾ƒåŠŸèƒ½ã€é˜…è¯»ç»è¿‡éªŒè¯çš„è¯„è®ºï¼Œæ‰¾åˆ°é€‚åˆæ‚¨å·¥ä½œæµç¨‹çš„å®Œç¾ŽAIè§£å†³æ–¹æ¡ˆã€‚",
    "hero.searchPlaceholder": "æœç´¢AIå·¥å…·ã€åˆ†ç±»æˆ–ç”¨ä¾‹...",
    "hero.searchButton": "æœç´¢",
    "hero.aiSearchHint": "è¯•è¯•ï¼š\"ç”¨äºŽæ’°å†™è¥é”€æ–‡æ¡ˆçš„AI\"",
    "stats.tools": "AIå·¥å…·",
    "stats.categories": "åˆ†ç±»",
    "stats.users": "æœˆæ´»ç”¨æˆ·",
    "stats.reviews": "è¯„è®º",
    "categories.title": "æŒ‰åˆ†ç±»æµè§ˆ",
    "categories.subtitle": "ä¸ºä»»ä½•ç”¨ä¾‹æ‰¾åˆ°å®Œç¾Žçš„AIå·¥å…·",
    "categories.viewAll": "æŸ¥çœ‹æ‰€æœ‰åˆ†ç±»",
    "featured.title": "ç²¾é€‰AIå·¥å…·",
    "featured.subtitle": "æœ¬å‘¨æˆ‘ä»¬çš„ç¤¾åŒºå–œçˆ±çš„ç²¾é€‰å·¥å…·",
    "featured.viewAll": "æŸ¥çœ‹æ‰€æœ‰å·¥å…·",
    "directory.title": "æŽ¢ç´¢ç›®å½•",
    "directory.subtitle": "ç­›é€‰ã€æœç´¢å¹¶å‘çŽ°é€‚åˆæ‚¨éœ€æ±‚çš„AIå·¥å…·",
    "directory.results": "ä¸ªå·¥å…·",
    "directory.filters": "ç­›é€‰å™¨",
    "directory.sortBy": "æŽ’åºæ–¹å¼",
    "directory.category": "åˆ†ç±»",
    "directory.pricing": "ä»·æ ¼",
    "directory.rating": "è¯„åˆ†",
    "directory.sort.popular": "æœ€çƒ­é—¨",
    "directory.sort.rated": "è¯„åˆ†æœ€é«˜",
    "directory.sort.newest": "æœ€æ–°",
    "directory.sort.priceLow": "ä»·æ ¼ï¼šä»Žä½Žåˆ°é«˜",
    "directory.sort.priceHigh": "ä»·æ ¼ï¼šä»Žé«˜åˆ°ä½Ž",
    "directory.empty": "æ²¡æœ‰å·¥å…·åŒ¹é…æ‚¨çš„ç­›é€‰æ¡ä»¶ã€‚è¯·å°è¯•è°ƒæ•´æœç´¢ã€‚",
    "directory.clearFilters": "æ¸…é™¤æ‰€æœ‰ç­›é€‰å™¨",
    "directory.loadMore": "åŠ è½½æ›´å¤šå·¥å…·",
    "pricing.free": "å…è´¹",
    "pricing.freemium": "å…è´¹å¢žå€¼",
    "pricing.paid": "ä»˜è´¹",
    "pricing.freeTrial": "å…è´¹è¯•ç”¨",
    "pricing.contactPricing": "è”ç³»èŽ·å–æŠ¥ä»·",
    "pricing.perMonth": "/æœˆ",
    "pricing.perYear": "/å¹´",
    "pricing.title": "ç®€å•é€æ˜Žçš„ä»·æ ¼",
    "pricing.subtitle": "é€‰æ‹©é€‚åˆæ‚¨éœ€æ±‚çš„è®¡åˆ’ã€‚éšæ—¶å–æ¶ˆã€‚",
    "pricing.monthly": "æœˆä»˜",
    "pricing.yearly": "å¹´ä»˜",
    "pricing.save": "èŠ‚çœ20%",
    "pricing.popular": "æœ€å—æ¬¢è¿Ž",
    "pricing.cta.free": "å…è´¹å¼€å§‹",
    "pricing.cta.pro": "å¼€å§‹Proè¯•ç”¨",
    "pricing.cta.business": "å¼€å§‹å•†ä¸šè¯•ç”¨",
    "pricing.cta.enterprise": "è”ç³»é”€å”®",
    "pricing.cta.currentPlan": "å½“å‰è®¡åˆ’",
    "compare.title": "å¹¶æŽ’æ¯”è¾ƒAIå·¥å…·",
    "compare.subtitle": "æ·»åŠ å·¥å…·ä»¥æ¯”è¾ƒåŠŸèƒ½ã€ä»·æ ¼å’Œè¯„åˆ†",
    "compare.addButton": "æ·»åŠ å·¥å…·è¿›è¡Œæ¯”è¾ƒ",
    "compare.remove": "ç§»é™¤",
    "compare.clearAll": "å…¨éƒ¨æ¸…é™¤",
    "compare.empty": "è‡³å°‘æ·»åŠ 2ä¸ªå·¥å…·æ‰èƒ½å¼€å§‹æ¯”è¾ƒ",
    "compare.feature": "åŠŸèƒ½",
    "compare.pricing": "ä»·æ ¼",
    "compare.rating": "è¯„åˆ†",
    "compare.reviews": "è¯„è®º",
    "compare.category": "åˆ†ç±»",
    "compare.tags": "æ ‡ç­¾",
    "compare.website": "ç½‘ç«™",
    "compare.addedAt": "æ·»åŠ äºŽ",
    "userDashboard.title": "æ‚¨çš„æŽ§åˆ¶å°",
    "userDashboard.subtitle": "ç®¡ç†æ‚¨çš„ä¹¦ç­¾ã€æ”¶è—å’Œè¯„è®º",
    "userDashboard.overview": "æ¦‚è§ˆ",
    "userDashboard.bookmarks": "ä¹¦ç­¾",
    "userDashboard.collections": "æ”¶è—",
    "userDashboard.reviews": "è¯„è®º",
    "userDashboard.analytics": "åˆ†æž",
    "userDashboard.totalBookmarks": "ä¹¦ç­¾æ€»æ•°",
    "userDashboard.totalCollections": "æ”¶è—æ•°",
    "userDashboard.totalReviews": "å·²å†™è¯„è®º",
    "userDashboard.recentActivity": "æœ€è¿‘æ´»åŠ¨",
    "adminDashboard.title": "ç®¡ç†æŽ§åˆ¶å°",
    "adminDashboard.subtitle": "ç®¡ç†å·¥å…·ã€ç”¨æˆ·å’Œå¹³å°åˆ†æž",
    "adminDashboard.tools": "å·¥å…·",
    "adminDashboard.analytics": "åˆ†æž",
    "adminDashboard.moderation": "å®¡æ ¸",
    "adminDashboard.users": "ç”¨æˆ·",
    "adminDashboard.auditLogs": "å®¡è®¡æ—¥å¿—",
    "adminDashboard.totalTools": "å·¥å…·æ€»æ•°",
    "adminDashboard.totalUsers": "ç”¨æˆ·æ€»æ•°",
    "adminDashboard.mrr": "æœˆæ”¶å…¥",
    "adminDashboard.pendingReviews": "å¾…å®¡è¯„è®º",
    "cta.title": "å‡†å¤‡å¥½æ”¹å˜æ‚¨çš„å·¥ä½œæµç¨‹äº†å—ï¼Ÿ",
    "cta.subtitle": "åŠ å…¥200å¤šä¸‡ä½¿ç”¨AIToolsHubæ‰¾åˆ°å®Œç¾ŽAIæŠ€æœ¯æ ˆçš„åˆ›ä½œè€…ã€å¼€å‘è€…å’Œä¼ä¸šã€‚",
    "cta.button": "ä»Šå¤©å…è´¹å¼€å§‹",
    "footer.about": "å…³äºŽ",
    "footer.product": "äº§å“",
    "footer.resources": "èµ„æº",
    "footer.legal": "æ³•å¾‹",
    "footer.company": "å…¬å¸",
    "footer.rights": "ä¿ç•™æ‰€æœ‰æƒåˆ©ã€‚",
    "footer.madeWith": "ç”¨å¿ƒåˆ¶ä½œ",
    "footer.forCreators": "ä¸ºåˆ›ä½œè€…",
    "common.viewDetails": "æŸ¥çœ‹è¯¦æƒ…",
    "common.visit": "è®¿é—®ç½‘ç«™",
    "common.bookmark": "ä¹¦ç­¾",
    "common.bookmarked": "å·²æ”¶è—",
    "common.share": "åˆ†äº«",
    "common.compare": "å¯¹æ¯”",
    "common.added": "å·²æ·»åŠ ",
    "common.free": "å…è´¹",
    "common.features": "åŠŸèƒ½",
    "common.pricing": "ä»·æ ¼",
    "common.reviews": "è¯„è®º",
    "common.alternatives": "æ›¿ä»£å“",
    "common.screenshots": "æˆªå›¾",
    "common.verified": "å·²éªŒè¯",
    "common.sponsored": "èµžåŠ©",
    "common.featured": "ç²¾é€‰",
    "common.search": "æœç´¢",
    "common.close": "å…³é—­",
    "common.apply": "åº”ç”¨",
    "common.cancel": "å–æ¶ˆ",
    "common.all": "å…¨éƒ¨",
  },
  hi: {
    "nav.discover": "à¤–à¥‹à¤œà¥‡à¤‚",
    "nav.categories": "à¤¶à¥à¤°à¥‡à¤£à¤¿à¤¯à¤¾à¤",
    "nav.compare": "à¤¤à¥à¤²à¤¨à¤¾",
    "nav.pricing": "à¤®à¥‚à¤²à¥à¤¯",
    "nav.blog": "à¤¬à¥à¤²à¥‰à¤—",
    "nav.api": "API à¤¦à¤¸à¥à¤¤à¤¾à¤µà¥‡à¤œà¤¼",
    "nav.signIn": "à¤¸à¤¾à¤‡à¤¨ à¤‡à¤¨",
    "nav.signUp": "à¤¶à¥à¤°à¥‚ à¤•à¤°à¥‡à¤‚",
    "nav.dashboard": "à¤¡à¥ˆà¤¶à¤¬à¥‹à¤°à¥à¤¡",
    "hero.badge": "à¤¦à¥à¤¨à¤¿à¤¯à¤¾ à¤­à¤° à¤®à¥‡à¤‚ 2M+ à¤°à¤šà¤¨à¤¾à¤•à¤¾à¤°à¥‹à¤‚ à¤¦à¥à¤µà¤¾à¤°à¤¾ à¤­à¤°à¥‹à¤¸à¤¾ à¤•à¤¿à¤¯à¤¾ à¤—à¤¯à¤¾",
    "hero.title": "à¤¸à¤°à¥à¤µà¤¶à¥à¤°à¥‡à¤·à¥à¤  AI à¤Ÿà¥‚à¤² à¤–à¥‹à¤œà¥‡à¤‚, à¤šà¤¯à¤¨à¤¿à¤¤ à¤”à¤° à¤°à¥ˆà¤‚à¤• à¤•à¤¿à¤ à¤—à¤",
    "hero.subtitle": "50+ à¤¶à¥à¤°à¥‡à¤£à¤¿à¤¯à¥‹à¤‚ à¤®à¥‡à¤‚ 100,000+ AI à¤Ÿà¥‚à¤² à¤à¤•à¥à¤¸à¤ªà¥à¤²à¥‹à¤° à¤•à¤°à¥‡à¤‚à¥¤ à¤µà¤¿à¤¶à¥‡à¤·à¤¤à¤¾à¤“à¤‚ à¤•à¥€ à¤¤à¥à¤²à¤¨à¤¾ à¤•à¤°à¥‡à¤‚, à¤¸à¤¤à¥à¤¯à¤¾à¤ªà¤¿à¤¤ à¤¸à¤®à¥€à¤•à¥à¤·à¤¾à¤à¤ à¤ªà¤¢à¤¼à¥‡à¤‚, à¤”à¤° à¤…à¤ªà¤¨à¥‡ à¤µà¤°à¥à¤•à¤«à¤¼à¥à¤²à¥‹ à¤•à¥‡ à¤²à¤¿à¤ à¤¸à¤¹à¥€ AI à¤¸à¤®à¤¾à¤§à¤¾à¤¨ à¤–à¥‹à¤œà¥‡à¤‚à¥¤",
    "hero.searchPlaceholder": "AI à¤Ÿà¥‚à¤², à¤¶à¥à¤°à¥‡à¤£à¤¿à¤¯à¤¾à¤, à¤¯à¤¾ à¤‰à¤ªà¤¯à¥‹à¤— à¤•à¥‡ à¤®à¤¾à¤®à¤²à¥‡ à¤–à¥‹à¤œà¥‡à¤‚...",
    "hero.searchButton": "à¤–à¥‹à¤œ",
    "hero.aiSearchHint": "à¤†à¤œà¤¼à¤®à¤¾à¤à¤: \"à¤®à¤¾à¤°à¥à¤•à¥‡à¤Ÿà¤¿à¤‚à¤— à¤•à¥‰à¤ªà¥€ à¤²à¤¿à¤–à¤¨à¥‡ à¤•à¥‡ à¤²à¤¿à¤ AI\"",
    "stats.tools": "AI à¤Ÿà¥‚à¤²",
    "stats.categories": "à¤¶à¥à¤°à¥‡à¤£à¤¿à¤¯à¤¾à¤",
    "stats.users": "à¤®à¤¾à¤¸à¤¿à¤• à¤‰à¤ªà¤¯à¥‹à¤—à¤•à¤°à¥à¤¤à¤¾",
    "stats.reviews": "à¤¸à¤®à¥€à¤•à¥à¤·à¤¾à¤à¤",
    "categories.title": "à¤¶à¥à¤°à¥‡à¤£à¥€ à¤¦à¥à¤µà¤¾à¤°à¤¾ à¤¬à¥à¤°à¤¾à¤‰à¤œà¤¼ à¤•à¤°à¥‡à¤‚",
    "categories.subtitle": "à¤•à¤¿à¤¸à¥€ à¤­à¥€ à¤‰à¤ªà¤¯à¥‹à¤— à¤•à¥‡ à¤²à¤¿à¤ à¤¸à¤¹à¥€ AI à¤Ÿà¥‚à¤² à¤–à¥‹à¤œà¥‡à¤‚",
    "categories.viewAll": "à¤¸à¤­à¥€ à¤¶à¥à¤°à¥‡à¤£à¤¿à¤¯à¤¾à¤ à¤¦à¥‡à¤–à¥‡à¤‚",
    "featured.title": "à¤«à¤¼à¥€à¤šà¤°à¥à¤¡ AI à¤Ÿà¥‚à¤²",
    "featured.subtitle": "à¤‡à¤¸ à¤¸à¤ªà¥à¤¤à¤¾à¤¹ à¤¹à¤®à¤¾à¤°à¥‡ à¤¸à¤®à¥à¤¦à¤¾à¤¯ à¤¦à¥à¤µà¤¾à¤°à¤¾ à¤ªà¤¸à¤‚à¤¦ à¤•à¤¿à¤ à¤—à¤ à¤šà¥à¤¨à¥‡ à¤¹à¥à¤ à¤Ÿà¥‚à¤²",
    "featured.viewAll": "à¤¸à¤­à¥€ à¤Ÿà¥‚à¤² à¤¦à¥‡à¤–à¥‡à¤‚",
    "directory.title": "à¤¡à¤¾à¤¯à¤°à¥‡à¤•à¥à¤Ÿà¤°à¥€ à¤à¤•à¥à¤¸à¤ªà¥à¤²à¥‹à¤° à¤•à¤°à¥‡à¤‚",
    "directory.subtitle": "à¤«à¤¼à¤¿à¤²à¥à¤Ÿà¤° à¤•à¤°à¥‡à¤‚, à¤–à¥‹à¤œà¥‡à¤‚, à¤”à¤° à¤…à¤ªà¤¨à¥€ à¤œà¤¼à¤°à¥‚à¤°à¤¤à¥‹à¤‚ à¤¸à¥‡ à¤®à¥‡à¤² à¤–à¤¾à¤¨à¥‡ à¤µà¤¾à¤²à¥‡ AI à¤Ÿà¥‚à¤² à¤–à¥‹à¤œà¥‡à¤‚",
    "directory.results": "à¤Ÿà¥‚à¤² à¤®à¤¿à¤²à¥‡",
    "directory.filters": "à¤«à¤¼à¤¿à¤²à¥à¤Ÿà¤°",
    "directory.sortBy": "à¤•à¥à¤°à¤®à¤¬à¤¦à¥à¤§ à¤•à¤°à¥‡à¤‚",
    "directory.category": "à¤¶à¥à¤°à¥‡à¤£à¥€",
    "directory.pricing": "à¤®à¥‚à¤²à¥à¤¯",
    "directory.rating": "à¤°à¥‡à¤Ÿà¤¿à¤‚à¤—",
    "directory.sort.popular": "à¤¸à¤¬à¤¸à¥‡ à¤²à¥‹à¤•à¤ªà¥à¤°à¤¿à¤¯",
    "directory.sort.rated": "à¤‰à¤šà¥à¤šà¤¤à¤® à¤°à¥‡à¤Ÿà¥‡à¤¡",
    "directory.sort.newest": "à¤¨à¤µà¥€à¤¨à¤¤à¤®",
    "directory.sort.priceLow": "à¤®à¥‚à¤²à¥à¤¯: à¤•à¤® à¤¸à¥‡ à¤…à¤§à¤¿à¤•",
    "directory.sort.priceHigh": "à¤®à¥‚à¤²à¥à¤¯: à¤…à¤§à¤¿à¤• à¤¸à¥‡ à¤•à¤®",
    "directory.empty": "à¤†à¤ªà¤•à¥‡ à¤«à¤¼à¤¿à¤²à¥à¤Ÿà¤° à¤¸à¥‡ à¤•à¥‹à¤ˆ à¤Ÿà¥‚à¤² à¤®à¥‡à¤² à¤¨à¤¹à¥€à¤‚ à¤–à¤¾à¤¤à¤¾à¥¤ à¤…à¤ªà¤¨à¥€ à¤–à¥‹à¤œ à¤¸à¤®à¤¾à¤¯à¥‹à¤œà¤¿à¤¤ à¤•à¤°à¤¨à¥‡ à¤•à¤¾ à¤ªà¥à¤°à¤¯à¤¾à¤¸ à¤•à¤°à¥‡à¤‚à¥¤",
    "directory.clearFilters": "à¤¸à¤­à¥€ à¤«à¤¼à¤¿à¤²à¥à¤Ÿà¤° à¤¸à¤¾à¤«à¤¼ à¤•à¤°à¥‡à¤‚",
    "directory.loadMore": "à¤”à¤° à¤Ÿà¥‚à¤² à¤²à¥‹à¤¡ à¤•à¤°à¥‡à¤‚",
    "pricing.free": "à¤®à¥à¤«à¤¼à¥à¤¤",
    "pricing.freemium": "à¤«à¥à¤°à¥€à¤®à¤¿à¤¯à¤®",
    "pricing.paid": "à¤¸à¤¶à¥à¤²à¥à¤•",
    "pricing.freeTrial": "à¤®à¥à¤«à¤¼à¥à¤¤ à¤ªà¤°à¥€à¤•à¥à¤·à¤£",
    "pricing.contactPricing": "à¤®à¥‚à¤²à¥à¤¯ à¤•à¥‡ à¤²à¤¿à¤ à¤¸à¤‚à¤ªà¤°à¥à¤• à¤•à¤°à¥‡à¤‚",
    "pricing.perMonth": "/à¤®à¤¾à¤¹",
    "pricing.perYear": "/à¤µà¤°à¥à¤·",
    "pricing.title": "à¤¸à¤°à¤², à¤ªà¤¾à¤°à¤¦à¤°à¥à¤¶à¥€ à¤®à¥‚à¤²à¥à¤¯ à¤¨à¤¿à¤°à¥à¤§à¤¾à¤°à¤£",
    "pricing.subtitle": "à¤…à¤ªà¤¨à¥€ à¤œà¤¼à¤°à¥‚à¤°à¤¤à¥‹à¤‚ à¤•à¥‡ à¤…à¤¨à¥à¤¸à¤¾à¤° à¤¯à¥‹à¤œà¤¨à¤¾ à¤šà¥à¤¨à¥‡à¤‚à¥¤ à¤•à¤­à¥€ à¤­à¥€ à¤°à¤¦à¥à¤¦ à¤•à¤°à¥‡à¤‚à¥¤",
    "pricing.monthly": "à¤®à¤¾à¤¸à¤¿à¤•",
    "pricing.yearly": "à¤µà¤¾à¤°à¥à¤·à¤¿à¤•",
    "pricing.save": "20% à¤¬à¤šà¤¾à¤à¤",
    "pricing.popular": "à¤¸à¤¬à¤¸à¥‡ à¤²à¥‹à¤•à¤ªà¥à¤°à¤¿à¤¯",
    "pricing.cta.free": "à¤®à¥à¤«à¤¼à¥à¤¤ à¤¶à¥à¤°à¥‚ à¤•à¤°à¥‡à¤‚",
    "pricing.cta.pro": "Pro à¤ªà¤°à¥€à¤•à¥à¤·à¤£ à¤¶à¥à¤°à¥‚ à¤•à¤°à¥‡à¤‚",
    "pricing.cta.business": "à¤¬à¤¿à¤œà¤¼à¤¨à¥‡à¤¸ à¤ªà¤°à¥€à¤•à¥à¤·à¤£ à¤¶à¥à¤°à¥‚ à¤•à¤°à¥‡à¤‚",
    "pricing.cta.enterprise": "à¤¬à¤¿à¤•à¥à¤°à¥€ à¤¸à¥‡ à¤¸à¤‚à¤ªà¤°à¥à¤• à¤•à¤°à¥‡à¤‚",
    "pricing.cta.currentPlan": "à¤µà¤°à¥à¤¤à¤®à¤¾à¤¨ à¤¯à¥‹à¤œà¤¨à¤¾",
    "compare.title": "AI à¤Ÿà¥‚à¤² à¤•à¥€ à¤†à¤®à¤¨à¥‡-à¤¸à¤¾à¤®à¤¨à¥‡ à¤¤à¥à¤²à¤¨à¤¾ à¤•à¤°à¥‡à¤‚",
    "compare.subtitle": "à¤µà¤¿à¤¶à¥‡à¤·à¤¤à¤¾à¤“à¤‚, à¤®à¥‚à¤²à¥à¤¯ à¤”à¤° à¤°à¥‡à¤Ÿà¤¿à¤‚à¤— à¤•à¥€ à¤¤à¥à¤²à¤¨à¤¾ à¤•à¥‡ à¤²à¤¿à¤ à¤Ÿà¥‚à¤² à¤œà¥‹à¤¡à¤¼à¥‡à¤‚",
    "compare.addButton": "à¤¤à¥à¤²à¤¨à¤¾ à¤•à¥‡ à¤²à¤¿à¤ à¤Ÿà¥‚à¤² à¤œà¥‹à¤¡à¤¼à¥‡à¤‚",
    "compare.remove": "à¤¹à¤Ÿà¤¾à¤à¤",
    "compare.clearAll": "à¤¸à¤­à¥€ à¤¸à¤¾à¤«à¤¼ à¤•à¤°à¥‡à¤‚",
    "compare.empty": "à¤¤à¥à¤²à¤¨à¤¾ à¤¶à¥à¤°à¥‚ à¤•à¤°à¤¨à¥‡ à¤•à¥‡ à¤²à¤¿à¤ à¤•à¤® à¤¸à¥‡ à¤•à¤® 2 à¤Ÿà¥‚à¤² à¤œà¥‹à¤¡à¤¼à¥‡à¤‚",
    "compare.feature": "à¤µà¤¿à¤¶à¥‡à¤·à¤¤à¤¾",
    "compare.pricing": "à¤®à¥‚à¤²à¥à¤¯",
    "compare.rating": "à¤°à¥‡à¤Ÿà¤¿à¤‚à¤—",
    "compare.reviews": "à¤¸à¤®à¥€à¤•à¥à¤·à¤¾à¤à¤",
    "compare.category": "à¤¶à¥à¤°à¥‡à¤£à¥€",
    "compare.tags": "à¤Ÿà¥ˆà¤—",
    "compare.website": "à¤µà¥‡à¤¬à¤¸à¤¾à¤‡à¤Ÿ",
    "compare.addedAt": "à¤œà¥‹à¤¡à¤¼à¤¾ à¤—à¤¯à¤¾",
    "userDashboard.title": "à¤†à¤ªà¤•à¤¾ à¤¡à¥ˆà¤¶à¤¬à¥‹à¤°à¥à¤¡",
    "userDashboard.subtitle": "à¤…à¤ªà¤¨à¥‡ à¤¬à¥à¤•à¤®à¤¾à¤°à¥à¤•, à¤¸à¤‚à¤—à¥à¤°à¤¹ à¤”à¤° à¤¸à¤®à¥€à¤•à¥à¤·à¤¾à¤à¤ à¤ªà¥à¤°à¤¬à¤‚à¤§à¤¿à¤¤ à¤•à¤°à¥‡à¤‚",
    "userDashboard.overview": "à¤…à¤µà¤²à¥‹à¤•à¤¨",
    "userDashboard.bookmarks": "à¤¬à¥à¤•à¤®à¤¾à¤°à¥à¤•",
    "userDashboard.collections": "à¤¸à¤‚à¤—à¥à¤°à¤¹",
    "userDashboard.reviews": "à¤¸à¤®à¥€à¤•à¥à¤·à¤¾à¤à¤",
    "userDashboard.analytics": "à¤à¤¨à¤¾à¤²à¤¿à¤Ÿà¤¿à¤•à¥à¤¸",
    "userDashboard.totalBookmarks": "à¤•à¥à¤² à¤¬à¥à¤•à¤®à¤¾à¤°à¥à¤•",
    "userDashboard.totalCollections": "à¤¸à¤‚à¤—à¥à¤°à¤¹",
    "userDashboard.totalReviews": "à¤²à¤¿à¤–à¥€ à¤—à¤ˆ à¤¸à¤®à¥€à¤•à¥à¤·à¤¾à¤à¤",
    "userDashboard.recentActivity": "à¤¹à¤¾à¤² à¤•à¥€ à¤—à¤¤à¤¿à¤µà¤¿à¤§à¤¿",
    "adminDashboard.title": "à¤à¤¡à¤®à¤¿à¤¨ à¤¡à¥ˆà¤¶à¤¬à¥‹à¤°à¥à¤¡",
    "adminDashboard.subtitle": "à¤Ÿà¥‚à¤², à¤‰à¤ªà¤¯à¥‹à¤—à¤•à¤°à¥à¤¤à¤¾ à¤”à¤° à¤ªà¥à¤²à¥‡à¤Ÿà¤«à¤¼à¥‰à¤°à¥à¤® à¤à¤¨à¤¾à¤²à¤¿à¤Ÿà¤¿à¤•à¥à¤¸ à¤ªà¥à¤°à¤¬à¤‚à¤§à¤¿à¤¤ à¤•à¤°à¥‡à¤‚",
    "adminDashboard.tools": "à¤Ÿà¥‚à¤²",
    "adminDashboard.analytics": "à¤à¤¨à¤¾à¤²à¤¿à¤Ÿà¤¿à¤•à¥à¤¸",
    "adminDashboard.moderation": "à¤®à¥‰à¤¡à¤°à¥‡à¤¶à¤¨",
    "adminDashboard.users": "à¤‰à¤ªà¤¯à¥‹à¤—à¤•à¤°à¥à¤¤à¤¾",
    "adminDashboard.auditLogs": "à¤‘à¤¡à¤¿à¤Ÿ à¤²à¥‰à¤—",
    "adminDashboard.totalTools": "à¤•à¥à¤² à¤Ÿà¥‚à¤²",
    "adminDashboard.totalUsers": "à¤•à¥à¤² à¤‰à¤ªà¤¯à¥‹à¤—à¤•à¤°à¥à¤¤à¤¾",
    "adminDashboard.mrr": "à¤®à¤¾à¤¸à¤¿à¤• à¤°à¤¾à¤œà¤¸à¥à¤µ",
    "adminDashboard.pendingReviews": "à¤²à¤‚à¤¬à¤¿à¤¤ à¤¸à¤®à¥€à¤•à¥à¤·à¤¾à¤à¤",
    "cta.title": "à¤…à¤ªà¤¨à¥‡ à¤µà¤°à¥à¤•à¤«à¤¼à¥à¤²à¥‹ à¤•à¥‹ à¤¬à¤¦à¤²à¤¨à¥‡ à¤•à¥‡ à¤²à¤¿à¤ à¤¤à¥ˆà¤¯à¤¾à¤° à¤¹à¥ˆà¤‚?",
    "cta.subtitle": "AIToolsHub à¤•à¤¾ à¤‰à¤ªà¤¯à¥‹à¤— à¤•à¤°à¤•à¥‡ à¤…à¤ªà¤¨à¥‡ à¤ªà¤°à¤«à¥‡à¤•à¥à¤Ÿ AI à¤¸à¥à¤Ÿà¥ˆà¤• à¤•à¥‹ à¤–à¥‹à¤œà¤¨à¥‡ à¤µà¤¾à¤²à¥‡ 2M+ à¤°à¤šà¤¨à¤¾à¤•à¤¾à¤°à¥‹à¤‚, à¤¡à¥‡à¤µà¤²à¤ªà¤°à¥à¤¸ à¤”à¤° à¤µà¥à¤¯à¤µà¤¸à¤¾à¤¯à¥‹à¤‚ à¤®à¥‡à¤‚ à¤¶à¤¾à¤®à¤¿à¤² à¤¹à¥‹à¤‚à¥¤",
    "cta.button": "à¤†à¤œ à¤®à¥à¤«à¤¼à¥à¤¤ à¤¶à¥à¤°à¥‚ à¤•à¤°à¥‡à¤‚",
    "footer.about": "à¤•à¥‡ à¤¬à¤¾à¤°à¥‡ à¤®à¥‡à¤‚",
    "footer.product": "à¤‰à¤¤à¥à¤ªà¤¾à¤¦",
    "footer.resources": "à¤¸à¤‚à¤¸à¤¾à¤§à¤¨",
    "footer.legal": "à¤•à¤¾à¤¨à¥‚à¤¨à¥€",
    "footer.company": "à¤•à¤‚à¤ªà¤¨à¥€",
    "footer.rights": "à¤¸à¤°à¥à¤µà¤¾à¤§à¤¿à¤•à¤¾à¤° à¤¸à¥à¤°à¤•à¥à¤·à¤¿à¤¤à¥¤",
    "footer.madeWith": "à¤•à¥‡ à¤¸à¤¾à¤¥ à¤¬à¤¨à¤¾à¤¯à¤¾ à¤—à¤¯à¤¾",
    "footer.forCreators": "à¤°à¤šà¤¨à¤¾à¤•à¤¾à¤°à¥‹à¤‚ à¤•à¥‡ à¤²à¤¿à¤",
    "common.viewDetails": "à¤µà¤¿à¤µà¤°à¤£ à¤¦à¥‡à¤–à¥‡à¤‚",
    "common.visit": "à¤µà¥‡à¤¬à¤¸à¤¾à¤‡à¤Ÿ à¤ªà¤° à¤œà¤¾à¤à¤",
    "common.bookmark": "à¤¬à¥à¤•à¤®à¤¾à¤°à¥à¤•",
    "common.bookmarked": "à¤¬à¥à¤•à¤®à¤¾à¤°à¥à¤• à¤•à¤¿à¤¯à¤¾ à¤—à¤¯à¤¾",
    "common.share": "à¤¸à¤¾à¤à¤¾ à¤•à¤°à¥‡à¤‚",
    "common.compare": "à¤¤à¥à¤²à¤¨à¤¾",
    "common.added": "à¤œà¥‹à¤¡à¤¼à¤¾ à¤—à¤¯à¤¾",
    "common.free": "à¤®à¥à¤«à¤¼à¥à¤¤",
    "common.features": "à¤µà¤¿à¤¶à¥‡à¤·à¤¤à¤¾à¤à¤",
    "common.pricing": "à¤®à¥‚à¤²à¥à¤¯",
    "common.reviews": "à¤¸à¤®à¥€à¤•à¥à¤·à¤¾à¤à¤",
    "common.alternatives": "à¤µà¤¿à¤•à¤²à¥à¤ª",
    "common.screenshots": "à¤¸à¥à¤•à¥à¤°à¥€à¤¨à¤¶à¥‰à¤Ÿ",
    "common.verified": "à¤¸à¤¤à¥à¤¯à¤¾à¤ªà¤¿à¤¤",
    "common.sponsored": "à¤ªà¥à¤°à¤¾à¤¯à¥‹à¤œà¤¿à¤¤",
    "common.featured": "à¤«à¤¼à¥€à¤šà¤°à¥à¤¡",
    "common.search": "à¤–à¥‹à¤œ",
    "common.close": "à¤¬à¤‚à¤¦ à¤•à¤°à¥‡à¤‚",
    "common.apply": "à¤²à¤¾à¤—à¥‚ à¤•à¤°à¥‡à¤‚",
    "common.cancel": "à¤°à¤¦à¥à¤¦ à¤•à¤°à¥‡à¤‚",
    "common.all": "à¤¸à¤­à¥€",
  },
};